/*
 * This file is generated by jOOQ.
 */
package io.zerows.extension.module.rbac.domain.tables.daos;


import io.r2mo.vertx.jooq.classic.jdbc.JDBCClassicQueryExecutor;
import io.r2mo.vertx.jooq.shared.internal.AbstractVertxDAO;
import io.vertx.core.Future;
import io.zerows.extension.module.rbac.domain.tables.SPermSet;
import io.zerows.extension.module.rbac.domain.tables.records.SPermSetRecord;
import org.jooq.Configuration;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class SPermSetDao extends AbstractVertxDAO<SPermSetRecord, io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet, String, Future<List<io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet>>, Future<io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet>, Future<Integer>, Future<String>> implements io.r2mo.vertx.jooq.classic.VertxDAO<SPermSetRecord, io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet, String> {

    /**
     * @param configuration The Configuration used for rendering and query
     *                      execution.
     * @param vertx         the vertx instance
     */
    public SPermSetDao(final Configuration configuration, final io.vertx.core.Vertx vertx) {
        super(SPermSet.S_PERM_SET, io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet.class, new JDBCClassicQueryExecutor<SPermSetRecord, io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet, String>(configuration, io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet.class, vertx));
    }

    @Override
    protected String getId(final io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet object) {
        return object.getKey();
    }

    /**
     * Find records that have <code>NAME IN (values)</code> asynchronously
     */
    public Future<List<io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet>> findManyByName(final Collection<String> values) {
        return findManyByCondition(SPermSet.S_PERM_SET.NAME.in(values));
    }

    /**
     * Find records that have <code>NAME IN (values)</code> asynchronously
     * limited by the given limit
     */
    public Future<List<io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet>> findManyByName(final Collection<String> values, final int limit) {
        return findManyByCondition(SPermSet.S_PERM_SET.NAME.in(values), limit);
    }

    /**
     * Find records that have <code>CODE IN (values)</code> asynchronously
     */
    public Future<List<io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet>> findManyByCode(final Collection<String> values) {
        return findManyByCondition(SPermSet.S_PERM_SET.CODE.in(values));
    }

    /**
     * Find records that have <code>CODE IN (values)</code> asynchronously
     * limited by the given limit
     */
    public Future<List<io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet>> findManyByCode(final Collection<String> values, final int limit) {
        return findManyByCondition(SPermSet.S_PERM_SET.CODE.in(values), limit);
    }

    /**
     * Find records that have <code>TYPE IN (values)</code> asynchronously
     */
    public Future<List<io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet>> findManyByType(final Collection<String> values) {
        return findManyByCondition(SPermSet.S_PERM_SET.TYPE.in(values));
    }

    /**
     * Find records that have <code>TYPE IN (values)</code> asynchronously
     * limited by the given limit
     */
    public Future<List<io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet>> findManyByType(final Collection<String> values, final int limit) {
        return findManyByCondition(SPermSet.S_PERM_SET.TYPE.in(values), limit);
    }

    /**
     * Find records that have <code>SIGMA IN (values)</code> asynchronously
     */
    public Future<List<io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet>> findManyBySigma(final Collection<String> values) {
        return findManyByCondition(SPermSet.S_PERM_SET.SIGMA.in(values));
    }

    /**
     * Find records that have <code>SIGMA IN (values)</code> asynchronously
     * limited by the given limit
     */
    public Future<List<io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet>> findManyBySigma(final Collection<String> values, final int limit) {
        return findManyByCondition(SPermSet.S_PERM_SET.SIGMA.in(values), limit);
    }

    /**
     * Find records that have <code>LANGUAGE IN (values)</code> asynchronously
     */
    public Future<List<io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet>> findManyByLanguage(final Collection<String> values) {
        return findManyByCondition(SPermSet.S_PERM_SET.LANGUAGE.in(values));
    }

    /**
     * Find records that have <code>LANGUAGE IN (values)</code> asynchronously
     * limited by the given limit
     */
    public Future<List<io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet>> findManyByLanguage(final Collection<String> values, final int limit) {
        return findManyByCondition(SPermSet.S_PERM_SET.LANGUAGE.in(values), limit);
    }

    /**
     * Find records that have <code>ACTIVE IN (values)</code> asynchronously
     */
    public Future<List<io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet>> findManyByActive(final Collection<Boolean> values) {
        return findManyByCondition(SPermSet.S_PERM_SET.ACTIVE.in(values));
    }

    /**
     * Find records that have <code>ACTIVE IN (values)</code> asynchronously
     * limited by the given limit
     */
    public Future<List<io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet>> findManyByActive(final Collection<Boolean> values, final int limit) {
        return findManyByCondition(SPermSet.S_PERM_SET.ACTIVE.in(values), limit);
    }

    /**
     * Find records that have <code>COMMENT IN (values)</code> asynchronously
     */
    public Future<List<io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet>> findManyByComment(final Collection<String> values) {
        return findManyByCondition(SPermSet.S_PERM_SET.COMMENT.in(values));
    }

    /**
     * Find records that have <code>COMMENT IN (values)</code> asynchronously
     * limited by the given limit
     */
    public Future<List<io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet>> findManyByComment(final Collection<String> values, final int limit) {
        return findManyByCondition(SPermSet.S_PERM_SET.COMMENT.in(values), limit);
    }

    /**
     * Find records that have <code>METADATA IN (values)</code> asynchronously
     */
    public Future<List<io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet>> findManyByMetadata(final Collection<String> values) {
        return findManyByCondition(SPermSet.S_PERM_SET.METADATA.in(values));
    }

    /**
     * Find records that have <code>METADATA IN (values)</code> asynchronously
     * limited by the given limit
     */
    public Future<List<io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet>> findManyByMetadata(final Collection<String> values, final int limit) {
        return findManyByCondition(SPermSet.S_PERM_SET.METADATA.in(values), limit);
    }

    /**
     * Find records that have <code>CREATED_AT IN (values)</code> asynchronously
     */
    public Future<List<io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet>> findManyByCreatedAt(final Collection<LocalDateTime> values) {
        return findManyByCondition(SPermSet.S_PERM_SET.CREATED_AT.in(values));
    }

    /**
     * Find records that have <code>CREATED_AT IN (values)</code> asynchronously
     * limited by the given limit
     */
    public Future<List<io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet>> findManyByCreatedAt(final Collection<LocalDateTime> values, final int limit) {
        return findManyByCondition(SPermSet.S_PERM_SET.CREATED_AT.in(values), limit);
    }

    /**
     * Find records that have <code>CREATED_BY IN (values)</code> asynchronously
     */
    public Future<List<io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet>> findManyByCreatedBy(final Collection<String> values) {
        return findManyByCondition(SPermSet.S_PERM_SET.CREATED_BY.in(values));
    }

    /**
     * Find records that have <code>CREATED_BY IN (values)</code> asynchronously
     * limited by the given limit
     */
    public Future<List<io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet>> findManyByCreatedBy(final Collection<String> values, final int limit) {
        return findManyByCondition(SPermSet.S_PERM_SET.CREATED_BY.in(values), limit);
    }

    /**
     * Find records that have <code>UPDATED_AT IN (values)</code> asynchronously
     */
    public Future<List<io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet>> findManyByUpdatedAt(final Collection<LocalDateTime> values) {
        return findManyByCondition(SPermSet.S_PERM_SET.UPDATED_AT.in(values));
    }

    /**
     * Find records that have <code>UPDATED_AT IN (values)</code> asynchronously
     * limited by the given limit
     */
    public Future<List<io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet>> findManyByUpdatedAt(final Collection<LocalDateTime> values, final int limit) {
        return findManyByCondition(SPermSet.S_PERM_SET.UPDATED_AT.in(values), limit);
    }

    /**
     * Find records that have <code>UPDATED_BY IN (values)</code> asynchronously
     */
    public Future<List<io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet>> findManyByUpdatedBy(final Collection<String> values) {
        return findManyByCondition(SPermSet.S_PERM_SET.UPDATED_BY.in(values));
    }

    /**
     * Find records that have <code>UPDATED_BY IN (values)</code> asynchronously
     * limited by the given limit
     */
    public Future<List<io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet>> findManyByUpdatedBy(final Collection<String> values, final int limit) {
        return findManyByCondition(SPermSet.S_PERM_SET.UPDATED_BY.in(values), limit);
    }

    @Override
    public JDBCClassicQueryExecutor<SPermSetRecord, io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet, String> queryExecutor() {
        return (JDBCClassicQueryExecutor<SPermSetRecord, io.zerows.extension.module.rbac.domain.tables.pojos.SPermSet, String>) super.queryExecutor();
    }
}
