/*
 * This file is generated by jOOQ.
 */
package io.zerows.extension.module.mbseapi.domain.tables;


import io.zerows.extension.module.mbseapi.domain.Indexes;
import io.zerows.extension.module.mbseapi.domain.Keys;
import io.zerows.extension.module.mbseapi.domain.Zdb;
import io.zerows.extension.module.mbseapi.domain.tables.records.IServiceRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 服务
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IService extends TableImpl<IServiceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ZDB.I_SERVICE</code>
     */
    public static final IService I_SERVICE = new IService();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IServiceRecord> getRecordType() {
        return IServiceRecord.class;
    }

    /**
     * The column <code>ZDB.I_SERVICE.ID</code>. 「id」- 主键
     */
    public final TableField<IServiceRecord, String> ID = createField(DSL.name("ID"), SQLDataType.VARCHAR(36).nullable(false), this, "「id」- 主键");

    /**
     * The column <code>ZDB.I_SERVICE.NAME</code>. 「name」- 名称
     */
    public final TableField<IServiceRecord, String> NAME = createField(DSL.name("NAME"), SQLDataType.VARCHAR(255), this, "「name」- 名称");

    /**
     * The column <code>ZDB.I_SERVICE.NAMESPACE</code>. 「namespace」- 名空间
     */
    public final TableField<IServiceRecord, String> NAMESPACE = createField(DSL.name("NAMESPACE"), SQLDataType.VARCHAR(255), this, "「namespace」- 名空间");

    /**
     * The column <code>ZDB.I_SERVICE.COMMENT</code>. 「comment」- 备注
     */
    public final TableField<IServiceRecord, String> COMMENT = createField(DSL.name("COMMENT"), SQLDataType.CLOB(65535), this, "「comment」- 备注");

    /**
     * The column <code>ZDB.I_SERVICE.IDENTIFIER</code>. 「identifier」- 模型标识
     */
    public final TableField<IServiceRecord, String> IDENTIFIER = createField(DSL.name("IDENTIFIER"), SQLDataType.VARCHAR(255), this, "「identifier」- 模型标识");

    /**
     * The column <code>ZDB.I_SERVICE.IDENTIFIER_COMPONENT</code>.
     * 「identifierComponent」- 标识组件
     */
    public final TableField<IServiceRecord, String> IDENTIFIER_COMPONENT = createField(DSL.name("IDENTIFIER_COMPONENT"), SQLDataType.VARCHAR(255), this, "「identifierComponent」- 标识组件");

    /**
     * The column <code>ZDB.I_SERVICE.RULE_UNIQUE</code>. 「ruleUnique」- 唯一规则
     */
    public final TableField<IServiceRecord, String> RULE_UNIQUE = createField(DSL.name("RULE_UNIQUE"), SQLDataType.CLOB(16777215), this, "「ruleUnique」- 唯一规则");

    /**
     * The column <code>ZDB.I_SERVICE.CHANNEL_TYPE</code>. 「channelType」- 通道类型
     */
    public final TableField<IServiceRecord, String> CHANNEL_TYPE = createField(DSL.name("CHANNEL_TYPE"), SQLDataType.VARCHAR(20), this, "「channelType」- 通道类型");

    /**
     * The column <code>ZDB.I_SERVICE.CHANNEL_COMPONENT</code>.
     * 「channelComponent」- 通道组件
     */
    public final TableField<IServiceRecord, String> CHANNEL_COMPONENT = createField(DSL.name("CHANNEL_COMPONENT"), SQLDataType.VARCHAR(255), this, "「channelComponent」- 通道组件");

    /**
     * The column <code>ZDB.I_SERVICE.CHANNEL_CONFIG</code>. 「channelConfig」-
     * 通道配置
     */
    public final TableField<IServiceRecord, String> CHANNEL_CONFIG = createField(DSL.name("CHANNEL_CONFIG"), SQLDataType.CLOB(16777215), this, "「channelConfig」- 通道配置");

    /**
     * The column <code>ZDB.I_SERVICE.DICT_COMPONENT</code>. 「dictComponent」-
     * 字典组件
     */
    public final TableField<IServiceRecord, String> DICT_COMPONENT = createField(DSL.name("DICT_COMPONENT"), SQLDataType.VARCHAR(255), this, "「dictComponent」- 字典组件");

    /**
     * The column <code>ZDB.I_SERVICE.DICT_CONFIG</code>. 「dictConfig」- 字典配置
     */
    public final TableField<IServiceRecord, String> DICT_CONFIG = createField(DSL.name("DICT_CONFIG"), SQLDataType.CLOB(16777215), this, "「dictConfig」- 字典配置");

    /**
     * The column <code>ZDB.I_SERVICE.DICT_EPSILON</code>. 「dictEpsilon」- 字典消费配置
     */
    public final TableField<IServiceRecord, String> DICT_EPSILON = createField(DSL.name("DICT_EPSILON"), SQLDataType.CLOB(16777215), this, "「dictEpsilon」- 字典消费配置");

    /**
     * The column <code>ZDB.I_SERVICE.MAPPING_MODE</code>. 「mappingMode」- 映射模式
     */
    public final TableField<IServiceRecord, String> MAPPING_MODE = createField(DSL.name("MAPPING_MODE"), SQLDataType.VARCHAR(20), this, "「mappingMode」- 映射模式");

    /**
     * The column <code>ZDB.I_SERVICE.MAPPING_COMPONENT</code>.
     * 「mappingComponent」- 映射组件
     */
    public final TableField<IServiceRecord, String> MAPPING_COMPONENT = createField(DSL.name("MAPPING_COMPONENT"), SQLDataType.VARCHAR(255), this, "「mappingComponent」- 映射组件");

    /**
     * The column <code>ZDB.I_SERVICE.MAPPING_CONFIG</code>. 「mappingConfig」-
     * 映射配置
     */
    public final TableField<IServiceRecord, String> MAPPING_CONFIG = createField(DSL.name("MAPPING_CONFIG"), SQLDataType.CLOB(16777215), this, "「mappingConfig」- 映射配置");

    /**
     * The column <code>ZDB.I_SERVICE.SERVICE_COMPONENT</code>.
     * 「serviceComponent」- 服务组件
     */
    public final TableField<IServiceRecord, String> SERVICE_COMPONENT = createField(DSL.name("SERVICE_COMPONENT"), SQLDataType.VARCHAR(255), this, "「serviceComponent」- 服务组件");

    /**
     * The column <code>ZDB.I_SERVICE.SERVICE_CONFIG</code>. 「serviceConfig」-
     * 业务配置
     */
    public final TableField<IServiceRecord, String> SERVICE_CONFIG = createField(DSL.name("SERVICE_CONFIG"), SQLDataType.CLOB(16777215), this, "「serviceConfig」- 业务配置");

    /**
     * The column <code>ZDB.I_SERVICE.SERVICE_RECORD</code>. 「serviceRecord」-
     * 服务记录
     */
    public final TableField<IServiceRecord, String> SERVICE_RECORD = createField(DSL.name("SERVICE_RECORD"), SQLDataType.VARCHAR(255), this, "「serviceRecord」- 服务记录");

    /**
     * The column <code>ZDB.I_SERVICE.CONFIG_DATABASE</code>. 「configDatabase」-
     * 数据库配置
     */
    public final TableField<IServiceRecord, String> CONFIG_DATABASE = createField(DSL.name("CONFIG_DATABASE"), SQLDataType.CLOB(16777215), this, "「configDatabase」- 数据库配置");

    /**
     * The column <code>ZDB.I_SERVICE.CONFIG_INTEGRATION</code>.
     * 「configIntegration」- 集成配置
     */
    public final TableField<IServiceRecord, String> CONFIG_INTEGRATION = createField(DSL.name("CONFIG_INTEGRATION"), SQLDataType.CLOB(16777215), this, "「configIntegration」- 集成配置");

    /**
     * The column <code>ZDB.I_SERVICE.IN_SCRIPT</code>. 「inScript」- 前置脚本
     */
    public final TableField<IServiceRecord, String> IN_SCRIPT = createField(DSL.name("IN_SCRIPT"), SQLDataType.CLOB(16777215), this, "「inScript」- 前置脚本");

    /**
     * The column <code>ZDB.I_SERVICE.OUT_SCRIPT</code>. 「outScript」- 后置脚本
     */
    public final TableField<IServiceRecord, String> OUT_SCRIPT = createField(DSL.name("OUT_SCRIPT"), SQLDataType.CLOB(16777215), this, "「outScript」- 后置脚本");

    /**
     * The column <code>ZDB.I_SERVICE.IS_GRAPHIC</code>. 「isGraphic」- 图引擎
     */
    public final TableField<IServiceRecord, Boolean> IS_GRAPHIC = createField(DSL.name("IS_GRAPHIC"), SQLDataType.BIT, this, "「isGraphic」- 图引擎");

    /**
     * The column <code>ZDB.I_SERVICE.IS_WORKFLOW</code>. 「isWorkflow」- 工作流
     */
    public final TableField<IServiceRecord, Boolean> IS_WORKFLOW = createField(DSL.name("IS_WORKFLOW"), SQLDataType.BIT, this, "「isWorkflow」- 工作流");

    /**
     * The column <code>ZDB.I_SERVICE.TYPE</code>. 「type」- 类型
     */
    public final TableField<IServiceRecord, String> TYPE = createField(DSL.name("TYPE"), SQLDataType.VARCHAR(64), this, "「type」- 类型");

    /**
     * The column <code>ZDB.I_SERVICE.SIGMA</code>. 「sigma」- 统一标识
     */
    public final TableField<IServiceRecord, String> SIGMA = createField(DSL.name("SIGMA"), SQLDataType.VARCHAR(128), this, "「sigma」- 统一标识");

    /**
     * The column <code>ZDB.I_SERVICE.TENANT_ID</code>. 「tenantId」- 租户ID
     */
    public final TableField<IServiceRecord, String> TENANT_ID = createField(DSL.name("TENANT_ID"), SQLDataType.VARCHAR(36), this, "「tenantId」- 租户ID");

    /**
     * The column <code>ZDB.I_SERVICE.APP_ID</code>. 「appId」- 应用ID
     */
    public final TableField<IServiceRecord, String> APP_ID = createField(DSL.name("APP_ID"), SQLDataType.VARCHAR(36), this, "「appId」- 应用ID");

    /**
     * The column <code>ZDB.I_SERVICE.ACTIVE</code>. 「active」- 是否启用
     */
    public final TableField<IServiceRecord, Boolean> ACTIVE = createField(DSL.name("ACTIVE"), SQLDataType.BIT, this, "「active」- 是否启用");

    /**
     * The column <code>ZDB.I_SERVICE.LANGUAGE</code>. 「language」- 语言偏好
     */
    public final TableField<IServiceRecord, String> LANGUAGE = createField(DSL.name("LANGUAGE"), SQLDataType.VARCHAR(10), this, "「language」- 语言偏好");

    /**
     * The column <code>ZDB.I_SERVICE.METADATA</code>. 「metadata」- 元配置
     */
    public final TableField<IServiceRecord, String> METADATA = createField(DSL.name("METADATA"), SQLDataType.CLOB(65535), this, "「metadata」- 元配置");

    /**
     * The column <code>ZDB.I_SERVICE.VERSION</code>. 「version」- 版本号
     */
    public final TableField<IServiceRecord, String> VERSION = createField(DSL.name("VERSION"), SQLDataType.VARCHAR(64), this, "「version」- 版本号");

    /**
     * The column <code>ZDB.I_SERVICE.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    public final TableField<IServiceRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(0), this, "「createdAt」- 创建时间");

    /**
     * The column <code>ZDB.I_SERVICE.CREATED_BY</code>. 「createdBy」- 创建人
     */
    public final TableField<IServiceRecord, String> CREATED_BY = createField(DSL.name("CREATED_BY"), SQLDataType.VARCHAR(36), this, "「createdBy」- 创建人");

    /**
     * The column <code>ZDB.I_SERVICE.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    public final TableField<IServiceRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(0), this, "「updatedAt」- 更新时间");

    /**
     * The column <code>ZDB.I_SERVICE.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    public final TableField<IServiceRecord, String> UPDATED_BY = createField(DSL.name("UPDATED_BY"), SQLDataType.VARCHAR(36), this, "「updatedBy」- 更新人");

    private IService(Name alias, Table<IServiceRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private IService(Name alias, Table<IServiceRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("服务"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>ZDB.I_SERVICE</code> table reference
     */
    public IService(String alias) {
        this(DSL.name(alias), I_SERVICE);
    }

    /**
     * Create an aliased <code>ZDB.I_SERVICE</code> table reference
     */
    public IService(Name alias) {
        this(alias, I_SERVICE);
    }

    /**
     * Create a <code>ZDB.I_SERVICE</code> table reference
     */
    public IService() {
        this(DSL.name("I_SERVICE"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Zdb.ZDB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.I_SERVICE_IDX_I_SERVICE_SIGMA);
    }

    @Override
    public UniqueKey<IServiceRecord> getPrimaryKey() {
        return Keys.KEY_I_SERVICE_PRIMARY;
    }

    @Override
    public List<UniqueKey<IServiceRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_I_SERVICE_UK_I_SERVICE_NAME_NAMESPACE);
    }

    @Override
    public IService as(String alias) {
        return new IService(DSL.name(alias), this);
    }

    @Override
    public IService as(Name alias) {
        return new IService(alias, this);
    }

    @Override
    public IService as(Table<?> alias) {
        return new IService(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public IService rename(String name) {
        return new IService(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IService rename(Name name) {
        return new IService(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public IService rename(Table<?> name) {
        return new IService(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IService where(Condition condition) {
        return new IService(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IService where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IService where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IService where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IService where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IService where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IService where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IService where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IService whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IService whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
