/*
 * This file is generated by jOOQ.
 */
package io.zerows.extension.module.graphic.domain.tables.records;


import io.r2mo.vertx.jooq.shared.internal.VertxPojo;
import io.vertx.core.json.JsonObject;
import io.zerows.extension.module.graphic.domain.tables.GCluster;
import io.zerows.extension.module.graphic.domain.tables.interfaces.IGCluster;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


import static io.r2mo.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * G_CLUSTER
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GClusterRecord extends UpdatableRecordImpl<GClusterRecord> implements VertxPojo, IGCluster {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ZDB.G_CLUSTER.ID</code>. 「id」- 主键
     */
    @Override
    public GClusterRecord setId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_CLUSTER.ID</code>. 「id」- 主键
     */
    @Override
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>ZDB.G_CLUSTER.GRAPHIC_ID</code>. 「graphicId」 -
     * 它所关联的图实例ID
     */
    @Override
    public GClusterRecord setGraphicId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_CLUSTER.GRAPHIC_ID</code>. 「graphicId」 -
     * 它所关联的图实例ID
     */
    @Override
    public String getGraphicId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ZDB.G_CLUSTER.NAME</code>. 「name」- 名称
     */
    @Override
    public GClusterRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_CLUSTER.NAME</code>. 「name」- 名称
     */
    @Override
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ZDB.G_CLUSTER.RECORD_DATA</code>. 「recordData」 -
     * 组中存储的数据信息
     */
    @Override
    public GClusterRecord setRecordData(JsonObject value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_CLUSTER.RECORD_DATA</code>. 「recordData」 -
     * 组中存储的数据信息
     */
    @Override
    public JsonObject getRecordData() {
        return (JsonObject) get(3);
    }

    /**
     * Setter for <code>ZDB.G_CLUSTER.RECORD_KEY</code>. 「recordKey」 - 记录主键
     */
    @Override
    public GClusterRecord setRecordKey(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_CLUSTER.RECORD_KEY</code>. 「recordKey」 - 记录主键
     */
    @Override
    public String getRecordKey() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ZDB.G_CLUSTER.UI</code>. 「ui」 - ui配置专用
     */
    @Override
    public GClusterRecord setUi(JsonObject value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_CLUSTER.UI</code>. 「ui」 - ui配置专用
     */
    @Override
    public JsonObject getUi() {
        return (JsonObject) get(5);
    }

    /**
     * Setter for <code>ZDB.G_CLUSTER.X</code>. 「x」 - 当前组在图上的x坐标
     */
    @Override
    public GClusterRecord setX(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_CLUSTER.X</code>. 「x」 - 当前组在图上的x坐标
     */
    @Override
    public Integer getX() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>ZDB.G_CLUSTER.Y</code>. 「y」 - 当前组在图上的y坐标
     */
    @Override
    public GClusterRecord setY(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_CLUSTER.Y</code>. 「y」 - 当前组在图上的y坐标
     */
    @Override
    public Integer getY() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>ZDB.G_CLUSTER.SIGMA</code>. 「sigma」- 统一标识
     */
    @Override
    public GClusterRecord setSigma(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_CLUSTER.SIGMA</code>. 「sigma」- 统一标识
     */
    @Override
    public String getSigma() {
        return (String) get(8);
    }

    /**
     * Setter for <code>ZDB.G_CLUSTER.TENANT_ID</code>. 「tenantId」- 租户ID
     */
    @Override
    public GClusterRecord setTenantId(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_CLUSTER.TENANT_ID</code>. 「tenantId」- 租户ID
     */
    @Override
    public String getTenantId() {
        return (String) get(9);
    }

    /**
     * Setter for <code>ZDB.G_CLUSTER.APP_ID</code>. 「appId」- 应用ID
     */
    @Override
    public GClusterRecord setAppId(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_CLUSTER.APP_ID</code>. 「appId」- 应用ID
     */
    @Override
    public String getAppId() {
        return (String) get(10);
    }

    /**
     * Setter for <code>ZDB.G_CLUSTER.ACTIVE</code>. 「active」- 是否启用
     */
    @Override
    public GClusterRecord setActive(Boolean value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_CLUSTER.ACTIVE</code>. 「active」- 是否启用
     */
    @Override
    public Boolean getActive() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>ZDB.G_CLUSTER.LANGUAGE</code>. 「language」- 语言偏好
     */
    @Override
    public GClusterRecord setLanguage(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_CLUSTER.LANGUAGE</code>. 「language」- 语言偏好
     */
    @Override
    public String getLanguage() {
        return (String) get(12);
    }

    /**
     * Setter for <code>ZDB.G_CLUSTER.METADATA</code>. 「metadata」- 元配置
     */
    @Override
    public GClusterRecord setMetadata(JsonObject value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_CLUSTER.METADATA</code>. 「metadata」- 元配置
     */
    @Override
    public JsonObject getMetadata() {
        return (JsonObject) get(13);
    }

    /**
     * Setter for <code>ZDB.G_CLUSTER.VERSION</code>. 「version」- 版本号
     */
    @Override
    public GClusterRecord setVersion(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_CLUSTER.VERSION</code>. 「version」- 版本号
     */
    @Override
    public String getVersion() {
        return (String) get(14);
    }

    /**
     * Setter for <code>ZDB.G_CLUSTER.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    @Override
    public GClusterRecord setCreatedAt(LocalDateTime value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_CLUSTER.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    @Override
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>ZDB.G_CLUSTER.CREATED_BY</code>. 「createdBy」- 创建人
     */
    @Override
    public GClusterRecord setCreatedBy(String value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_CLUSTER.CREATED_BY</code>. 「createdBy」- 创建人
     */
    @Override
    public String getCreatedBy() {
        return (String) get(16);
    }

    /**
     * Setter for <code>ZDB.G_CLUSTER.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    @Override
    public GClusterRecord setUpdatedAt(LocalDateTime value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_CLUSTER.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    @Override
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(17);
    }

    /**
     * Setter for <code>ZDB.G_CLUSTER.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    @Override
    public GClusterRecord setUpdatedBy(String value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_CLUSTER.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    @Override
    public String getUpdatedBy() {
        return (String) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IGCluster from) {
        setId(from.getId());
        setGraphicId(from.getGraphicId());
        setName(from.getName());
        setRecordData(from.getRecordData());
        setRecordKey(from.getRecordKey());
        setUi(from.getUi());
        setX(from.getX());
        setY(from.getY());
        setSigma(from.getSigma());
        setTenantId(from.getTenantId());
        setAppId(from.getAppId());
        setActive(from.getActive());
        setLanguage(from.getLanguage());
        setMetadata(from.getMetadata());
        setVersion(from.getVersion());
        setCreatedAt(from.getCreatedAt());
        setCreatedBy(from.getCreatedBy());
        setUpdatedAt(from.getUpdatedAt());
        setUpdatedBy(from.getUpdatedBy());
        resetTouchedOnNotNull();
    }

    @Override
    public <E extends IGCluster> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GClusterRecord
     */
    public GClusterRecord() {
        super(GCluster.G_CLUSTER);
    }

    /**
     * Create a detached, initialised GClusterRecord
     */
    public GClusterRecord(String id, String graphicId, String name, JsonObject recordData, String recordKey, JsonObject ui, Integer x, Integer y, String sigma, String tenantId, String appId, Boolean active, String language, JsonObject metadata, String version, LocalDateTime createdAt, String createdBy, LocalDateTime updatedAt, String updatedBy) {
        super(GCluster.G_CLUSTER);

        setId(id);
        setGraphicId(graphicId);
        setName(name);
        setRecordData(recordData);
        setRecordKey(recordKey);
        setUi(ui);
        setX(x);
        setY(y);
        setSigma(sigma);
        setTenantId(tenantId);
        setAppId(appId);
        setActive(active);
        setLanguage(language);
        setMetadata(metadata);
        setVersion(version);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised GClusterRecord
     */
    public GClusterRecord(IGCluster value) {
        super(GCluster.G_CLUSTER);

        if (value != null) {
            setId(value.getId());
            setGraphicId(value.getGraphicId());
            setName(value.getName());
            setRecordData(value.getRecordData());
            setRecordKey(value.getRecordKey());
            setUi(value.getUi());
            setX(value.getX());
            setY(value.getY());
            setSigma(value.getSigma());
            setTenantId(value.getTenantId());
            setAppId(value.getAppId());
            setActive(value.getActive());
            setLanguage(value.getLanguage());
            setMetadata(value.getMetadata());
            setVersion(value.getVersion());
            setCreatedAt(value.getCreatedAt());
            setCreatedBy(value.getCreatedBy());
            setUpdatedAt(value.getUpdatedAt());
            setUpdatedBy(value.getUpdatedBy());
            resetTouchedOnNotNull();
        }
    }

        public GClusterRecord(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }
}
