/*
 * This file is generated by jOOQ.
 */
package io.zerows.extension.module.graphic.domain.tables.records;


import io.r2mo.vertx.jooq.shared.internal.VertxPojo;
import io.zerows.extension.module.graphic.domain.tables.GNode;
import io.zerows.extension.module.graphic.domain.tables.interfaces.IGNode;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


import static io.r2mo.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GNodeRecord extends UpdatableRecordImpl<GNodeRecord> implements VertxPojo, IGNode {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ZDB.G_NODE.KEY</code>. 「key」- 节点ID
     */
    @Override
    public GNodeRecord setKey(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_NODE.KEY</code>. 「key」- 节点ID
     */
    @Override
    public String getKey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>ZDB.G_NODE.NAME</code>. 「name」- 节点呈现名称
     */
    @Override
    public GNodeRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_NODE.NAME</code>. 「name」- 节点呈现名称
     */
    @Override
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ZDB.G_NODE.X</code>. 「x」- 当前节点在图上的x坐标
     */
    @Override
    public GNodeRecord setX(BigDecimal value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_NODE.X</code>. 「x」- 当前节点在图上的x坐标
     */
    @Override
    public BigDecimal getX() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>ZDB.G_NODE.Y</code>. 「y」- 当前节点在图上的y坐标
     */
    @Override
    public GNodeRecord setY(BigDecimal value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_NODE.Y</code>. 「y」- 当前节点在图上的y坐标
     */
    @Override
    public BigDecimal getY() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>ZDB.G_NODE.UI</code>. 「ui」- ui配置专用
     */
    @Override
    public GNodeRecord setUi(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_NODE.UI</code>. 「ui」- ui配置专用
     */
    @Override
    public String getUi() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ZDB.G_NODE.GRAPHIC_ID</code>. 「graphicId」- 它所关联的图实例ID
     */
    @Override
    public GNodeRecord setGraphicId(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_NODE.GRAPHIC_ID</code>. 「graphicId」- 它所关联的图实例ID
     */
    @Override
    public String getGraphicId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>ZDB.G_NODE.RECORD_DATA</code>. 「recordData」- 该节点存储的数据信息
     */
    @Override
    public GNodeRecord setRecordData(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_NODE.RECORD_DATA</code>. 「recordData」- 该节点存储的数据信息
     */
    @Override
    public String getRecordData() {
        return (String) get(6);
    }

    /**
     * Setter for <code>ZDB.G_NODE.RECORD_KEY</code>. 「recordKey」- 记录主键
     */
    @Override
    public GNodeRecord setRecordKey(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_NODE.RECORD_KEY</code>. 「recordKey」- 记录主键
     */
    @Override
    public String getRecordKey() {
        return (String) get(7);
    }

    /**
     * Setter for <code>ZDB.G_NODE.RECORD_COMPONENT</code>. 「recordComponent」-
     * 记录处理组件
     */
    @Override
    public GNodeRecord setRecordComponent(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_NODE.RECORD_COMPONENT</code>. 「recordComponent」-
     * 记录处理组件
     */
    @Override
    public String getRecordComponent() {
        return (String) get(8);
    }

    /**
     * Setter for <code>ZDB.G_NODE.RECORD_CLASS</code>. 「recordClass」-
     * 记录绑定Pojo类型
     */
    @Override
    public GNodeRecord setRecordClass(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_NODE.RECORD_CLASS</code>. 「recordClass」-
     * 记录绑定Pojo类型
     */
    @Override
    public String getRecordClass() {
        return (String) get(9);
    }

    /**
     * Setter for <code>ZDB.G_NODE.SIGMA</code>. 「sigma」- 用户组绑定的统一标识
     */
    @Override
    public GNodeRecord setSigma(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_NODE.SIGMA</code>. 「sigma」- 用户组绑定的统一标识
     */
    @Override
    public String getSigma() {
        return (String) get(10);
    }

    /**
     * Setter for <code>ZDB.G_NODE.LANGUAGE</code>. 「language」- 使用的语言
     */
    @Override
    public GNodeRecord setLanguage(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_NODE.LANGUAGE</code>. 「language」- 使用的语言
     */
    @Override
    public String getLanguage() {
        return (String) get(11);
    }

    /**
     * Setter for <code>ZDB.G_NODE.ACTIVE</code>. 「active」- 是否启用
     */
    @Override
    public GNodeRecord setActive(Boolean value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_NODE.ACTIVE</code>. 「active」- 是否启用
     */
    @Override
    public Boolean getActive() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>ZDB.G_NODE.METADATA</code>. 「metadata」- 附加配置数据
     */
    @Override
    public GNodeRecord setMetadata(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_NODE.METADATA</code>. 「metadata」- 附加配置数据
     */
    @Override
    public String getMetadata() {
        return (String) get(13);
    }

    /**
     * Setter for <code>ZDB.G_NODE.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    @Override
    public GNodeRecord setCreatedAt(LocalDateTime value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_NODE.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    @Override
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>ZDB.G_NODE.CREATED_BY</code>. 「createdBy」- 创建人
     */
    @Override
    public GNodeRecord setCreatedBy(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_NODE.CREATED_BY</code>. 「createdBy」- 创建人
     */
    @Override
    public String getCreatedBy() {
        return (String) get(15);
    }

    /**
     * Setter for <code>ZDB.G_NODE.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    @Override
    public GNodeRecord setUpdatedAt(LocalDateTime value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_NODE.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    @Override
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(16);
    }

    /**
     * Setter for <code>ZDB.G_NODE.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    @Override
    public GNodeRecord setUpdatedBy(String value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_NODE.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    @Override
    public String getUpdatedBy() {
        return (String) get(17);
    }

    /**
     * Setter for <code>ZDB.G_NODE.APP_ID</code>. 「appId」- 应用ID
     */
    @Override
    public GNodeRecord setAppId(String value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_NODE.APP_ID</code>. 「appId」- 应用ID
     */
    @Override
    public String getAppId() {
        return (String) get(18);
    }

    /**
     * Setter for <code>ZDB.G_NODE.TENANT_ID</code>. 「tenantId」- 租户ID
     */
    @Override
    public GNodeRecord setTenantId(String value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.G_NODE.TENANT_ID</code>. 「tenantId」- 租户ID
     */
    @Override
    public String getTenantId() {
        return (String) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IGNode from) {
        setKey(from.getKey());
        setName(from.getName());
        setX(from.getX());
        setY(from.getY());
        setUi(from.getUi());
        setGraphicId(from.getGraphicId());
        setRecordData(from.getRecordData());
        setRecordKey(from.getRecordKey());
        setRecordComponent(from.getRecordComponent());
        setRecordClass(from.getRecordClass());
        setSigma(from.getSigma());
        setLanguage(from.getLanguage());
        setActive(from.getActive());
        setMetadata(from.getMetadata());
        setCreatedAt(from.getCreatedAt());
        setCreatedBy(from.getCreatedBy());
        setUpdatedAt(from.getUpdatedAt());
        setUpdatedBy(from.getUpdatedBy());
        setAppId(from.getAppId());
        setTenantId(from.getTenantId());
        resetTouchedOnNotNull();
    }

    @Override
    public <E extends IGNode> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GNodeRecord
     */
    public GNodeRecord() {
        super(GNode.G_NODE);
    }

    /**
     * Create a detached, initialised GNodeRecord
     */
    public GNodeRecord(String key, String name, BigDecimal x, BigDecimal y, String ui, String graphicId, String recordData, String recordKey, String recordComponent, String recordClass, String sigma, String language, Boolean active, String metadata, LocalDateTime createdAt, String createdBy, LocalDateTime updatedAt, String updatedBy, String appId, String tenantId) {
        super(GNode.G_NODE);

        setKey(key);
        setName(name);
        setX(x);
        setY(y);
        setUi(ui);
        setGraphicId(graphicId);
        setRecordData(recordData);
        setRecordKey(recordKey);
        setRecordComponent(recordComponent);
        setRecordClass(recordClass);
        setSigma(sigma);
        setLanguage(language);
        setActive(active);
        setMetadata(metadata);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
        setAppId(appId);
        setTenantId(tenantId);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised GNodeRecord
     */
    public GNodeRecord(IGNode value) {
        super(GNode.G_NODE);

        if (value != null) {
            setKey(value.getKey());
            setName(value.getName());
            setX(value.getX());
            setY(value.getY());
            setUi(value.getUi());
            setGraphicId(value.getGraphicId());
            setRecordData(value.getRecordData());
            setRecordKey(value.getRecordKey());
            setRecordComponent(value.getRecordComponent());
            setRecordClass(value.getRecordClass());
            setSigma(value.getSigma());
            setLanguage(value.getLanguage());
            setActive(value.getActive());
            setMetadata(value.getMetadata());
            setCreatedAt(value.getCreatedAt());
            setCreatedBy(value.getCreatedBy());
            setUpdatedAt(value.getUpdatedAt());
            setUpdatedBy(value.getUpdatedBy());
            setAppId(value.getAppId());
            setTenantId(value.getTenantId());
            resetTouchedOnNotNull();
        }
    }

        public GNodeRecord(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }
}
