/*
 * This file is generated by jOOQ.
 */
package io.zerows.extension.module.tpl.domain.tables.records;


import io.r2mo.vertx.jooq.shared.internal.VertxPojo;
import io.zerows.extension.module.tpl.domain.tables.MyFavor;
import io.zerows.extension.module.tpl.domain.tables.interfaces.IMyFavor;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class MyFavorRecord extends UpdatableRecordImpl<MyFavorRecord> implements VertxPojo, IMyFavor {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached MyFavorRecord
     */
    public MyFavorRecord() {
        super(MyFavor.MY_FAVOR);
    }

    /**
     * Create a detached, initialised MyFavorRecord
     */
    public MyFavorRecord(String key, String owner, String ownerType, Long uiSort, String type, String position, String uriKey, String uriFull, String uri, String uriParam, String sigma, String language, Boolean active, String metadata, LocalDateTime createdAt, String createdBy, LocalDateTime updatedAt, String updatedBy, String appId, String tenantId) {
        super(MyFavor.MY_FAVOR);

        setKey(key);
        setOwner(owner);
        setOwnerType(ownerType);
        setUiSort(uiSort);
        setType(type);
        setPosition(position);
        setUriKey(uriKey);
        setUriFull(uriFull);
        setUri(uri);
        setUriParam(uriParam);
        setSigma(sigma);
        setLanguage(language);
        setActive(active);
        setMetadata(metadata);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
        setAppId(appId);
        setTenantId(tenantId);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised MyFavorRecord
     */
    public MyFavorRecord(IMyFavor value) {
        super(MyFavor.MY_FAVOR);

        if (value != null) {
            setKey(value.getKey());
            setOwner(value.getOwner());
            setOwnerType(value.getOwnerType());
            setUiSort(value.getUiSort());
            setType(value.getType());
            setPosition(value.getPosition());
            setUriKey(value.getUriKey());
            setUriFull(value.getUriFull());
            setUri(value.getUri());
            setUriParam(value.getUriParam());
            setSigma(value.getSigma());
            setLanguage(value.getLanguage());
            setActive(value.getActive());
            setMetadata(value.getMetadata());
            setCreatedAt(value.getCreatedAt());
            setCreatedBy(value.getCreatedBy());
            setUpdatedAt(value.getUpdatedAt());
            setUpdatedBy(value.getUpdatedBy());
            setAppId(value.getAppId());
            setTenantId(value.getTenantId());
            resetTouchedOnNotNull();
        }
    }

    public MyFavorRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    /**
     * Getter for <code>ZDB.MY_FAVOR.KEY</code>. 「key」- 个人应用主键
     */
    @Override
    public String getKey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>ZDB.MY_FAVOR.KEY</code>. 「key」- 个人应用主键
     */
    @Override
    public MyFavorRecord setKey(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_FAVOR.OWNER</code>. 「owner」- 拥有者ID，我的 / 角色级
     */
    @Override
    public String getOwner() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ZDB.MY_FAVOR.OWNER</code>. 「owner」- 拥有者ID，我的 / 角色级
     */
    @Override
    public MyFavorRecord setOwner(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_FAVOR.OWNER_TYPE</code>. 「ownerType」- ROLE
     * 角色，USER 用户
     */
    @Override
    public String getOwnerType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ZDB.MY_FAVOR.OWNER_TYPE</code>. 「ownerType」- ROLE
     * 角色，USER 用户
     */
    @Override
    public MyFavorRecord setOwnerType(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_FAVOR.UI_SORT</code>. 「uiSort」- 模块排序
     */
    @Override
    public Long getUiSort() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>ZDB.MY_FAVOR.UI_SORT</code>. 「uiSort」- 模块排序
     */
    @Override
    public MyFavorRecord setUiSort(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_FAVOR.TYPE</code>. 「type」- 类型（默认全站）
     */
    @Override
    public String getType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ZDB.MY_FAVOR.TYPE</code>. 「type」- 类型（默认全站）
     */
    @Override
    public MyFavorRecord setType(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_FAVOR.POSITION</code>. 「position」- 位置（默认左侧）
     */
    @Override
    public String getPosition() {
        return (String) get(5);
    }

    /**
     * Setter for <code>ZDB.MY_FAVOR.POSITION</code>. 「position」- 位置（默认左侧）
     */
    @Override
    public MyFavorRecord setPosition(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_FAVOR.URI_KEY</code>. 「uriKey」- URI KEY（加密长度）
     */
    @Override
    public String getUriKey() {
        return (String) get(6);
    }

    /**
     * Setter for <code>ZDB.MY_FAVOR.URI_KEY</code>. 「uriKey」- URI KEY（加密长度）
     */
    @Override
    public MyFavorRecord setUriKey(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_FAVOR.URI_FULL</code>. 「uriFull」- 收藏完整链接地址（带参数部分）
     */
    @Override
    public String getUriFull() {
        return (String) get(7);
    }

    /**
     * Setter for <code>ZDB.MY_FAVOR.URI_FULL</code>. 「uriFull」- 收藏完整链接地址（带参数部分）
     */
    @Override
    public MyFavorRecord setUriFull(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_FAVOR.URI</code>. 「uri」- 收藏地址
     */
    @Override
    public String getUri() {
        return (String) get(8);
    }

    /**
     * Setter for <code>ZDB.MY_FAVOR.URI</code>. 「uri」- 收藏地址
     */
    @Override
    public MyFavorRecord setUri(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_FAVOR.URI_PARAM</code>. 「uriParam」- 该收藏参数（收藏夹专用）
     */
    @Override
    public String getUriParam() {
        return (String) get(9);
    }

    /**
     * Setter for <code>ZDB.MY_FAVOR.URI_PARAM</code>. 「uriParam」- 该收藏参数（收藏夹专用）
     */
    @Override
    public MyFavorRecord setUriParam(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_FAVOR.SIGMA</code>. 「sigma」- 用户组绑定的统一标识
     */
    @Override
    public String getSigma() {
        return (String) get(10);
    }

    /**
     * Setter for <code>ZDB.MY_FAVOR.SIGMA</code>. 「sigma」- 用户组绑定的统一标识
     */
    @Override
    public MyFavorRecord setSigma(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_FAVOR.LANGUAGE</code>. 「language」- 使用的语言
     */
    @Override
    public String getLanguage() {
        return (String) get(11);
    }

    /**
     * Setter for <code>ZDB.MY_FAVOR.LANGUAGE</code>. 「language」- 使用的语言
     */
    @Override
    public MyFavorRecord setLanguage(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_FAVOR.ACTIVE</code>. 「active」- 是否启用
     */
    @Override
    public Boolean getActive() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>ZDB.MY_FAVOR.ACTIVE</code>. 「active」- 是否启用
     */
    @Override
    public MyFavorRecord setActive(Boolean value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_FAVOR.METADATA</code>. 「metadata」- 附加配置数据
     */
    @Override
    public String getMetadata() {
        return (String) get(13);
    }

    /**
     * Setter for <code>ZDB.MY_FAVOR.METADATA</code>. 「metadata」- 附加配置数据
     */
    @Override
    public MyFavorRecord setMetadata(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_FAVOR.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    @Override
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>ZDB.MY_FAVOR.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    @Override
    public MyFavorRecord setCreatedAt(LocalDateTime value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_FAVOR.CREATED_BY</code>. 「createdBy」- 创建人
     */
    @Override
    public String getCreatedBy() {
        return (String) get(15);
    }

    /**
     * Setter for <code>ZDB.MY_FAVOR.CREATED_BY</code>. 「createdBy」- 创建人
     */
    @Override
    public MyFavorRecord setCreatedBy(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_FAVOR.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    @Override
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(16);
    }

    /**
     * Setter for <code>ZDB.MY_FAVOR.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    @Override
    public MyFavorRecord setUpdatedAt(LocalDateTime value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_FAVOR.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    @Override
    public String getUpdatedBy() {
        return (String) get(17);
    }

    /**
     * Setter for <code>ZDB.MY_FAVOR.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    @Override
    public MyFavorRecord setUpdatedBy(String value) {
        set(17, value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>ZDB.MY_FAVOR.APP_ID</code>. 「appId」- 应用ID
     */
    @Override
    public String getAppId() {
        return (String) get(18);
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>ZDB.MY_FAVOR.APP_ID</code>. 「appId」- 应用ID
     */
    @Override
    public MyFavorRecord setAppId(String value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_FAVOR.TENANT_ID</code>. 「tenantId」- 租户ID
     */
    @Override
    public String getTenantId() {
        return (String) get(19);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>ZDB.MY_FAVOR.TENANT_ID</code>. 「tenantId」- 租户ID
     */
    @Override
    public MyFavorRecord setTenantId(String value) {
        set(19, value);
        return this;
    }

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    @Override
    public void from(IMyFavor from) {
        setKey(from.getKey());
        setOwner(from.getOwner());
        setOwnerType(from.getOwnerType());
        setUiSort(from.getUiSort());
        setType(from.getType());
        setPosition(from.getPosition());
        setUriKey(from.getUriKey());
        setUriFull(from.getUriFull());
        setUri(from.getUri());
        setUriParam(from.getUriParam());
        setSigma(from.getSigma());
        setLanguage(from.getLanguage());
        setActive(from.getActive());
        setMetadata(from.getMetadata());
        setCreatedAt(from.getCreatedAt());
        setCreatedBy(from.getCreatedBy());
        setUpdatedAt(from.getUpdatedAt());
        setUpdatedBy(from.getUpdatedBy());
        setAppId(from.getAppId());
        setTenantId(from.getTenantId());
        resetTouchedOnNotNull();
    }

    @Override
    public <E extends IMyFavor> E into(E into) {
        into.from(this);
        return into;
    }
}
