/*
 * This file is generated by jOOQ.
 */
package io.zerows.extension.module.tpl.domain.tables.records;


import io.r2mo.vertx.jooq.shared.internal.VertxPojo;
import io.zerows.extension.module.tpl.domain.tables.MySetting;
import io.zerows.extension.module.tpl.domain.tables.interfaces.IMySetting;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class MySettingRecord extends UpdatableRecordImpl<MySettingRecord> implements VertxPojo, IMySetting {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached MySettingRecord
     */
    public MySettingRecord() {
        super(MySetting.MY_SETTING);
    }

    /**
     * Create a detached, initialised MySettingRecord
     */
    public MySettingRecord(String key, String pNavTheme, String pColorPrimary, String pLayout, String pContentWidth, Boolean pFixedHeader, Boolean pFixSiderBar, Boolean pColorWeak, Boolean pPwa, String pToken, String myBag, String owner, String ownerType, String type, String sigma, String language, Boolean active, String metadata, LocalDateTime createdAt, String createdBy, LocalDateTime updatedAt, String updatedBy, String appId, String tenantId) {
        super(MySetting.MY_SETTING);

        setKey(key);
        setPNavTheme(pNavTheme);
        setPColorPrimary(pColorPrimary);
        setPLayout(pLayout);
        setPContentWidth(pContentWidth);
        setPFixedHeader(pFixedHeader);
        setPFixSiderBar(pFixSiderBar);
        setPColorWeak(pColorWeak);
        setPPwa(pPwa);
        setPToken(pToken);
        setMyBag(myBag);
        setOwner(owner);
        setOwnerType(ownerType);
        setType(type);
        setSigma(sigma);
        setLanguage(language);
        setActive(active);
        setMetadata(metadata);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
        setAppId(appId);
        setTenantId(tenantId);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised MySettingRecord
     */
    public MySettingRecord(IMySetting value) {
        super(MySetting.MY_SETTING);

        if (value != null) {
            setKey(value.getKey());
            setPNavTheme(value.getPNavTheme());
            setPColorPrimary(value.getPColorPrimary());
            setPLayout(value.getPLayout());
            setPContentWidth(value.getPContentWidth());
            setPFixedHeader(value.getPFixedHeader());
            setPFixSiderBar(value.getPFixSiderBar());
            setPColorWeak(value.getPColorWeak());
            setPPwa(value.getPPwa());
            setPToken(value.getPToken());
            setMyBag(value.getMyBag());
            setOwner(value.getOwner());
            setOwnerType(value.getOwnerType());
            setType(value.getType());
            setSigma(value.getSigma());
            setLanguage(value.getLanguage());
            setActive(value.getActive());
            setMetadata(value.getMetadata());
            setCreatedAt(value.getCreatedAt());
            setCreatedBy(value.getCreatedBy());
            setUpdatedAt(value.getUpdatedAt());
            setUpdatedBy(value.getUpdatedBy());
            setAppId(value.getAppId());
            setTenantId(value.getTenantId());
            resetTouchedOnNotNull();
        }
    }

    public MySettingRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    /**
     * Getter for <code>ZDB.MY_SETTING.KEY</code>. 「key」- 个人设置主键
     */
    @Override
    public String getKey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>ZDB.MY_SETTING.KEY</code>. 「key」- 个人设置主键
     */
    @Override
    public MySettingRecord setKey(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_SETTING.P_NAV_THEME</code>. 「pNavTheme」-
     * navTheme, 风格处理，对应 light / realdark
     */
    @Override
    public String getPNavTheme() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ZDB.MY_SETTING.P_NAV_THEME</code>. 「pNavTheme」-
     * navTheme, 风格处理，对应 light / realdark
     */
    @Override
    public MySettingRecord setPNavTheme(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_SETTING.P_COLOR_PRIMARY</code>. 「pColorPrimary」-
     * colorPrimary，主色调
     */
    @Override
    public String getPColorPrimary() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ZDB.MY_SETTING.P_COLOR_PRIMARY</code>. 「pColorPrimary」-
     * colorPrimary，主色调
     */
    @Override
    public MySettingRecord setPColorPrimary(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_SETTING.P_LAYOUT</code>. 「pLayout」- 布局类型：top,
     * menu, mix
     */
    @Override
    public String getPLayout() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ZDB.MY_SETTING.P_LAYOUT</code>. 「pLayout」- 布局类型：top,
     * menu, mix
     */
    @Override
    public MySettingRecord setPLayout(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_SETTING.P_CONTENT_WIDTH</code>. 「pContentWidth」-
     * 两种
     */
    @Override
    public String getPContentWidth() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ZDB.MY_SETTING.P_CONTENT_WIDTH</code>. 「pContentWidth」-
     * 两种
     */
    @Override
    public MySettingRecord setPContentWidth(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_SETTING.P_FIXED_HEADER</code>. 「pFixedHeader」-
     * 标题控制
     */
    @Override
    public Boolean getPFixedHeader() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>ZDB.MY_SETTING.P_FIXED_HEADER</code>. 「pFixedHeader」-
     * 标题控制
     */
    @Override
    public MySettingRecord setPFixedHeader(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_SETTING.P_FIX_SIDER_BAR</code>. 「pFixSiderBar」-
     * 侧边栏控制
     */
    @Override
    public Boolean getPFixSiderBar() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>ZDB.MY_SETTING.P_FIX_SIDER_BAR</code>. 「pFixSiderBar」-
     * 侧边栏控制
     */
    @Override
    public MySettingRecord setPFixSiderBar(Boolean value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_SETTING.P_COLOR_WEAK</code>. 「pColorWeak」- 色彩控制
     */
    @Override
    public Boolean getPColorWeak() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>ZDB.MY_SETTING.P_COLOR_WEAK</code>. 「pColorWeak」- 色彩控制
     */
    @Override
    public MySettingRecord setPColorWeak(Boolean value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_SETTING.P_PWA</code>. 「pPwa」- pwa属性，暂时未知
     */
    @Override
    public Boolean getPPwa() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>ZDB.MY_SETTING.P_PWA</code>. 「pPwa」- pwa属性，暂时未知
     */
    @Override
    public MySettingRecord setPPwa(Boolean value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_SETTING.P_TOKEN</code>. 「pToken」- 保留（后续可能会使用）
     */
    @Override
    public String getPToken() {
        return (String) get(9);
    }

    /**
     * Setter for <code>ZDB.MY_SETTING.P_TOKEN</code>. 「pToken」- 保留（后续可能会使用）
     */
    @Override
    public MySettingRecord setPToken(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_SETTING.MY_BAG</code>. 「myBag」- 对应 MY_BAG
     * 设置，每个BAG有对应设置信息
     */
    @Override
    public String getMyBag() {
        return (String) get(10);
    }

    /**
     * Setter for <code>ZDB.MY_SETTING.MY_BAG</code>. 「myBag」- 对应 MY_BAG
     * 设置，每个BAG有对应设置信息
     */
    @Override
    public MySettingRecord setMyBag(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_SETTING.OWNER</code>. 「owner」- 拥有者ID，我的 / 角色级
     */
    @Override
    public String getOwner() {
        return (String) get(11);
    }

    /**
     * Setter for <code>ZDB.MY_SETTING.OWNER</code>. 「owner」- 拥有者ID，我的 / 角色级
     */
    @Override
    public MySettingRecord setOwner(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_SETTING.OWNER_TYPE</code>. 「ownerType」- ROLE
     * 角色，USER 用户
     */
    @Override
    public String getOwnerType() {
        return (String) get(12);
    }

    /**
     * Setter for <code>ZDB.MY_SETTING.OWNER_TYPE</code>. 「ownerType」- ROLE
     * 角色，USER 用户
     */
    @Override
    public MySettingRecord setOwnerType(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_SETTING.TYPE</code>. 「type」- 类型（默认全站）
     */
    @Override
    public String getType() {
        return (String) get(13);
    }

    /**
     * Setter for <code>ZDB.MY_SETTING.TYPE</code>. 「type」- 类型（默认全站）
     */
    @Override
    public MySettingRecord setType(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_SETTING.SIGMA</code>. 「sigma」- 用户组绑定的统一标识
     */
    @Override
    public String getSigma() {
        return (String) get(14);
    }

    /**
     * Setter for <code>ZDB.MY_SETTING.SIGMA</code>. 「sigma」- 用户组绑定的统一标识
     */
    @Override
    public MySettingRecord setSigma(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_SETTING.LANGUAGE</code>. 「language」- 使用的语言
     */
    @Override
    public String getLanguage() {
        return (String) get(15);
    }

    /**
     * Setter for <code>ZDB.MY_SETTING.LANGUAGE</code>. 「language」- 使用的语言
     */
    @Override
    public MySettingRecord setLanguage(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_SETTING.ACTIVE</code>. 「active」- 是否启用
     */
    @Override
    public Boolean getActive() {
        return (Boolean) get(16);
    }

    /**
     * Setter for <code>ZDB.MY_SETTING.ACTIVE</code>. 「active」- 是否启用
     */
    @Override
    public MySettingRecord setActive(Boolean value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_SETTING.METADATA</code>. 「metadata」- 附加配置数据
     */
    @Override
    public String getMetadata() {
        return (String) get(17);
    }

    /**
     * Setter for <code>ZDB.MY_SETTING.METADATA</code>. 「metadata」- 附加配置数据
     */
    @Override
    public MySettingRecord setMetadata(String value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_SETTING.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    @Override
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(18);
    }

    /**
     * Setter for <code>ZDB.MY_SETTING.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    @Override
    public MySettingRecord setCreatedAt(LocalDateTime value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_SETTING.CREATED_BY</code>. 「createdBy」- 创建人
     */
    @Override
    public String getCreatedBy() {
        return (String) get(19);
    }

    /**
     * Setter for <code>ZDB.MY_SETTING.CREATED_BY</code>. 「createdBy」- 创建人
     */
    @Override
    public MySettingRecord setCreatedBy(String value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_SETTING.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    @Override
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(20);
    }

    /**
     * Setter for <code>ZDB.MY_SETTING.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    @Override
    public MySettingRecord setUpdatedAt(LocalDateTime value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_SETTING.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    @Override
    public String getUpdatedBy() {
        return (String) get(21);
    }

    /**
     * Setter for <code>ZDB.MY_SETTING.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    @Override
    public MySettingRecord setUpdatedBy(String value) {
        set(21, value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>ZDB.MY_SETTING.APP_ID</code>. 「appId」- 应用ID
     */
    @Override
    public String getAppId() {
        return (String) get(22);
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>ZDB.MY_SETTING.APP_ID</code>. 「appId」- 应用ID
     */
    @Override
    public MySettingRecord setAppId(String value) {
        set(22, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.MY_SETTING.TENANT_ID</code>. 「tenantId」- 租户ID
     */
    @Override
    public String getTenantId() {
        return (String) get(23);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>ZDB.MY_SETTING.TENANT_ID</code>. 「tenantId」- 租户ID
     */
    @Override
    public MySettingRecord setTenantId(String value) {
        set(23, value);
        return this;
    }

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    @Override
    public void from(IMySetting from) {
        setKey(from.getKey());
        setPNavTheme(from.getPNavTheme());
        setPColorPrimary(from.getPColorPrimary());
        setPLayout(from.getPLayout());
        setPContentWidth(from.getPContentWidth());
        setPFixedHeader(from.getPFixedHeader());
        setPFixSiderBar(from.getPFixSiderBar());
        setPColorWeak(from.getPColorWeak());
        setPPwa(from.getPPwa());
        setPToken(from.getPToken());
        setMyBag(from.getMyBag());
        setOwner(from.getOwner());
        setOwnerType(from.getOwnerType());
        setType(from.getType());
        setSigma(from.getSigma());
        setLanguage(from.getLanguage());
        setActive(from.getActive());
        setMetadata(from.getMetadata());
        setCreatedAt(from.getCreatedAt());
        setCreatedBy(from.getCreatedBy());
        setUpdatedAt(from.getUpdatedAt());
        setUpdatedBy(from.getUpdatedBy());
        setAppId(from.getAppId());
        setTenantId(from.getTenantId());
        resetTouchedOnNotNull();
    }

    @Override
    public <E extends IMySetting> E into(E into) {
        into.from(this);
        return into;
    }
}
