/*
 * This file is generated by jOOQ.
 */
package io.zerows.extension.commerce.finance.domain.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IFSettlementItem extends VertxPojo, Serializable {

    /**
     * Setter for <code>ZDB.F_SETTLEMENT_ITEM.KEY</code>. 「key」- 结算单明细主键
     */
    public IFSettlementItem setKey(String value);

    /**
     * Getter for <code>ZDB.F_SETTLEMENT_ITEM.KEY</code>. 「key」- 结算单明细主键
     */
    public String getKey();

    /**
     * Setter for <code>ZDB.F_SETTLEMENT_ITEM.NAME</code>. 「name」 -  明细名称
     */
    public IFSettlementItem setName(String value);

    /**
     * Getter for <code>ZDB.F_SETTLEMENT_ITEM.NAME</code>. 「name」 -  明细名称
     */
    public String getName();

    /**
     * Setter for <code>ZDB.F_SETTLEMENT_ITEM.CODE</code>. 「code」 - 明细系统代码
     */
    public IFSettlementItem setCode(String value);

    /**
     * Getter for <code>ZDB.F_SETTLEMENT_ITEM.CODE</code>. 「code」 - 明细系统代码
     */
    public String getCode();

    /**
     * Setter for <code>ZDB.F_SETTLEMENT_ITEM.SERIAL</code>. 「serial」 - 明细编号
     */
    public IFSettlementItem setSerial(String value);

    /**
     * Getter for <code>ZDB.F_SETTLEMENT_ITEM.SERIAL</code>. 「serial」 - 明细编号
     */
    public String getSerial();

    /**
     * Setter for <code>ZDB.F_SETTLEMENT_ITEM.INCOME</code>. 「income」- true =
     * 消费类，false = 付款类
     */
    public IFSettlementItem setIncome(Boolean value);

    /**
     * Getter for <code>ZDB.F_SETTLEMENT_ITEM.INCOME</code>. 「income」- true =
     * 消费类，false = 付款类
     */
    public Boolean getIncome();

    /**
     * Setter for <code>ZDB.F_SETTLEMENT_ITEM.TYPE</code>. 「type」- 明细类型
     */
    public IFSettlementItem setType(String value);

    /**
     * Getter for <code>ZDB.F_SETTLEMENT_ITEM.TYPE</code>. 「type」- 明细类型
     */
    public String getType();

    /**
     * Setter for <code>ZDB.F_SETTLEMENT_ITEM.AMOUNT</code>.
     * 「amount」——价税合计，实际结算金额
     */
    public IFSettlementItem setAmount(BigDecimal value);

    /**
     * Getter for <code>ZDB.F_SETTLEMENT_ITEM.AMOUNT</code>.
     * 「amount」——价税合计，实际结算金额
     */
    public BigDecimal getAmount();

    /**
     * Setter for <code>ZDB.F_SETTLEMENT_ITEM.COMMENT</code>. 「comment」 - 明细备注
     */
    public IFSettlementItem setComment(String value);

    /**
     * Getter for <code>ZDB.F_SETTLEMENT_ITEM.COMMENT</code>. 「comment」 - 明细备注
     */
    public String getComment();

    /**
     * Setter for <code>ZDB.F_SETTLEMENT_ITEM.START_AT</code>. 「startAt」- 开始时间
     */
    public IFSettlementItem setStartAt(LocalDateTime value);

    /**
     * Getter for <code>ZDB.F_SETTLEMENT_ITEM.START_AT</code>. 「startAt」- 开始时间
     */
    public LocalDateTime getStartAt();

    /**
     * Setter for <code>ZDB.F_SETTLEMENT_ITEM.END_AT</code>. 「endAt」- 结束时间
     */
    public IFSettlementItem setEndAt(LocalDateTime value);

    /**
     * Getter for <code>ZDB.F_SETTLEMENT_ITEM.END_AT</code>. 「endAt」- 结束时间
     */
    public LocalDateTime getEndAt();

    /**
     * Setter for <code>ZDB.F_SETTLEMENT_ITEM.GROUP_BY</code>. 「groupBy」- 分组
     */
    public IFSettlementItem setGroupBy(String value);

    /**
     * Getter for <code>ZDB.F_SETTLEMENT_ITEM.GROUP_BY</code>. 「groupBy」- 分组
     */
    public String getGroupBy();

    /**
     * Setter for <code>ZDB.F_SETTLEMENT_ITEM.MANUAL_NO</code>. 「manualNo」 -
     * 手工单号（线下单号专用）
     */
    public IFSettlementItem setManualNo(String value);

    /**
     * Getter for <code>ZDB.F_SETTLEMENT_ITEM.MANUAL_NO</code>. 「manualNo」 -
     * 手工单号（线下单号专用）
     */
    public String getManualNo();

    /**
     * Setter for <code>ZDB.F_SETTLEMENT_ITEM.PAY_TERM_ID</code>. 「payTermId」-
     * 账单项ID
     */
    public IFSettlementItem setPayTermId(String value);

    /**
     * Getter for <code>ZDB.F_SETTLEMENT_ITEM.PAY_TERM_ID</code>. 「payTermId」-
     * 账单项ID
     */
    public String getPayTermId();

    /**
     * Setter for <code>ZDB.F_SETTLEMENT_ITEM.RELATED_ID</code>. 「relatedId」-
     * 关联BillItem ID（保留，原系统存在）
     */
    public IFSettlementItem setRelatedId(String value);

    /**
     * Getter for <code>ZDB.F_SETTLEMENT_ITEM.RELATED_ID</code>. 「relatedId」-
     * 关联BillItem ID（保留，原系统存在）
     */
    public String getRelatedId();

    /**
     * Setter for <code>ZDB.F_SETTLEMENT_ITEM.SETTLEMENT_ID</code>.
     * 「settlementId」- 结算单ID，该字段有值标识已经结算
     */
    public IFSettlementItem setSettlementId(String value);

    /**
     * Getter for <code>ZDB.F_SETTLEMENT_ITEM.SETTLEMENT_ID</code>.
     * 「settlementId」- 结算单ID，该字段有值标识已经结算
     */
    public String getSettlementId();

    /**
     * Setter for <code>ZDB.F_SETTLEMENT_ITEM.DEBT_ID</code>. 「debtId」- 应收账单ID
     */
    public IFSettlementItem setDebtId(String value);

    /**
     * Getter for <code>ZDB.F_SETTLEMENT_ITEM.DEBT_ID</code>. 「debtId」- 应收账单ID
     */
    public String getDebtId();

    /**
     * Setter for <code>ZDB.F_SETTLEMENT_ITEM.FINISHED_ID</code>. 「finishedId」-
     * 关联交易ID
     */
    public IFSettlementItem setFinishedId(String value);

    /**
     * Getter for <code>ZDB.F_SETTLEMENT_ITEM.FINISHED_ID</code>. 「finishedId」-
     * 关联交易ID
     */
    public String getFinishedId();

    /**
     * Setter for <code>ZDB.F_SETTLEMENT_ITEM.SIGMA</code>. 「sigma」- 统一标识
     */
    public IFSettlementItem setSigma(String value);

    /**
     * Getter for <code>ZDB.F_SETTLEMENT_ITEM.SIGMA</code>. 「sigma」- 统一标识
     */
    public String getSigma();

    /**
     * Setter for <code>ZDB.F_SETTLEMENT_ITEM.LANGUAGE</code>. 「language」- 使用的语言
     */
    public IFSettlementItem setLanguage(String value);

    /**
     * Getter for <code>ZDB.F_SETTLEMENT_ITEM.LANGUAGE</code>. 「language」- 使用的语言
     */
    public String getLanguage();

    /**
     * Setter for <code>ZDB.F_SETTLEMENT_ITEM.ACTIVE</code>. 「active」- 是否启用
     */
    public IFSettlementItem setActive(Boolean value);

    /**
     * Getter for <code>ZDB.F_SETTLEMENT_ITEM.ACTIVE</code>. 「active」- 是否启用
     */
    public Boolean getActive();

    /**
     * Setter for <code>ZDB.F_SETTLEMENT_ITEM.METADATA</code>. 「metadata」-
     * 附加配置数据
     */
    public IFSettlementItem setMetadata(String value);

    /**
     * Getter for <code>ZDB.F_SETTLEMENT_ITEM.METADATA</code>. 「metadata」-
     * 附加配置数据
     */
    public String getMetadata();

    /**
     * Setter for <code>ZDB.F_SETTLEMENT_ITEM.CREATED_AT</code>. 「createdAt」-
     * 创建时间
     */
    public IFSettlementItem setCreatedAt(LocalDateTime value);

    /**
     * Getter for <code>ZDB.F_SETTLEMENT_ITEM.CREATED_AT</code>. 「createdAt」-
     * 创建时间
     */
    public LocalDateTime getCreatedAt();

    /**
     * Setter for <code>ZDB.F_SETTLEMENT_ITEM.CREATED_BY</code>. 「createdBy」-
     * 创建人
     */
    public IFSettlementItem setCreatedBy(String value);

    /**
     * Getter for <code>ZDB.F_SETTLEMENT_ITEM.CREATED_BY</code>. 「createdBy」-
     * 创建人
     */
    public String getCreatedBy();

    /**
     * Setter for <code>ZDB.F_SETTLEMENT_ITEM.UPDATED_AT</code>. 「updatedAt」-
     * 更新时间
     */
    public IFSettlementItem setUpdatedAt(LocalDateTime value);

    /**
     * Getter for <code>ZDB.F_SETTLEMENT_ITEM.UPDATED_AT</code>. 「updatedAt」-
     * 更新时间
     */
    public LocalDateTime getUpdatedAt();

    /**
     * Setter for <code>ZDB.F_SETTLEMENT_ITEM.UPDATED_BY</code>. 「updatedBy」-
     * 更新人
     */
    public IFSettlementItem setUpdatedBy(String value);

    /**
     * Getter for <code>ZDB.F_SETTLEMENT_ITEM.UPDATED_BY</code>. 「updatedBy」-
     * 更新人
     */
    public String getUpdatedBy();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IFSettlementItem
     */
    public void from(IFSettlementItem from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IFSettlementItem
     */
    public <E extends IFSettlementItem> E into(E into);

        @Override
        public default IFSettlementItem fromJson(io.vertx.core.json.JsonObject json) {
                setOrThrow(this::setKey,json::getString,"KEY","java.lang.String");
                setOrThrow(this::setName,json::getString,"NAME","java.lang.String");
                setOrThrow(this::setCode,json::getString,"CODE","java.lang.String");
                setOrThrow(this::setSerial,json::getString,"SERIAL","java.lang.String");
                setOrThrow(this::setIncome,json::getBoolean,"INCOME","java.lang.Boolean");
                setOrThrow(this::setType,json::getString,"TYPE","java.lang.String");
                setOrThrow(this::setAmount,key -> {String s = json.getString(key); return s==null?null:new java.math.BigDecimal(s);},"AMOUNT","java.math.BigDecimal");
                setOrThrow(this::setComment,json::getString,"COMMENT","java.lang.String");
                setOrThrow(this::setStartAt,key -> {String s = json.getString(key); return s==null?null:java.time.LocalDateTime.parse(s);},"START_AT","java.time.LocalDateTime");
                setOrThrow(this::setEndAt,key -> {String s = json.getString(key); return s==null?null:java.time.LocalDateTime.parse(s);},"END_AT","java.time.LocalDateTime");
                setOrThrow(this::setGroupBy,json::getString,"GROUP_BY","java.lang.String");
                setOrThrow(this::setManualNo,json::getString,"MANUAL_NO","java.lang.String");
                setOrThrow(this::setPayTermId,json::getString,"PAY_TERM_ID","java.lang.String");
                setOrThrow(this::setRelatedId,json::getString,"RELATED_ID","java.lang.String");
                setOrThrow(this::setSettlementId,json::getString,"SETTLEMENT_ID","java.lang.String");
                setOrThrow(this::setDebtId,json::getString,"DEBT_ID","java.lang.String");
                setOrThrow(this::setFinishedId,json::getString,"FINISHED_ID","java.lang.String");
                setOrThrow(this::setSigma,json::getString,"SIGMA","java.lang.String");
                setOrThrow(this::setLanguage,json::getString,"LANGUAGE","java.lang.String");
                setOrThrow(this::setActive,json::getBoolean,"ACTIVE","java.lang.Boolean");
                setOrThrow(this::setMetadata,json::getString,"METADATA","java.lang.String");
                setOrThrow(this::setCreatedAt,key -> {String s = json.getString(key); return s==null?null:java.time.LocalDateTime.parse(s);},"CREATED_AT","java.time.LocalDateTime");
                setOrThrow(this::setCreatedBy,json::getString,"CREATED_BY","java.lang.String");
                setOrThrow(this::setUpdatedAt,key -> {String s = json.getString(key); return s==null?null:java.time.LocalDateTime.parse(s);},"UPDATED_AT","java.time.LocalDateTime");
                setOrThrow(this::setUpdatedBy,json::getString,"UPDATED_BY","java.lang.String");
                return this;
        }


        @Override
        public default io.vertx.core.json.JsonObject toJson() {
                io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
                json.put("KEY",getKey());
                json.put("NAME",getName());
                json.put("CODE",getCode());
                json.put("SERIAL",getSerial());
                json.put("INCOME",getIncome());
                json.put("TYPE",getType());
                json.put("AMOUNT",getAmount()==null?null:getAmount().toString());
                json.put("COMMENT",getComment());
                json.put("START_AT",getStartAt()==null?null:getStartAt().toString());
                json.put("END_AT",getEndAt()==null?null:getEndAt().toString());
                json.put("GROUP_BY",getGroupBy());
                json.put("MANUAL_NO",getManualNo());
                json.put("PAY_TERM_ID",getPayTermId());
                json.put("RELATED_ID",getRelatedId());
                json.put("SETTLEMENT_ID",getSettlementId());
                json.put("DEBT_ID",getDebtId());
                json.put("FINISHED_ID",getFinishedId());
                json.put("SIGMA",getSigma());
                json.put("LANGUAGE",getLanguage());
                json.put("ACTIVE",getActive());
                json.put("METADATA",getMetadata());
                json.put("CREATED_AT",getCreatedAt()==null?null:getCreatedAt().toString());
                json.put("CREATED_BY",getCreatedBy());
                json.put("UPDATED_AT",getUpdatedAt()==null?null:getUpdatedAt().toString());
                json.put("UPDATED_BY",getUpdatedBy());
                return json;
        }

}
