-- 清空权限相关表
-- 注意：这会删除所有权限数据，请谨慎使用

-- 1. 清空角色权限关联表
DELETE FROM R_ROLE_PERM WHERE 1=1;

-- 2. 清空操作表
DELETE FROM S_ACTION WHERE 1=1;

-- 3. 清空资源表
DELETE FROM S_RESOURCE WHERE 1=1;

-- 4. 清空权限表
DELETE FROM S_PERMISSION WHERE 1=1;

-- 验证清空结果
SELECT 'R_ROLE_PERM' as table_name, COUNT(*) as count FROM R_ROLE_PERM
UNION ALL
SELECT 'S_ACTION', COUNT(*) FROM S_ACTION
UNION ALL
SELECT 'S_RESOURCE', COUNT(*) FROM S_RESOURCE
UNION ALL
SELECT 'S_PERMISSION', COUNT(*) FROM S_PERMISSION;
