/*
 * This file is generated by jOOQ.
 */
package io.zerows.extension.module.graphic.domain.tables.interfaces;


import io.r2mo.vertx.jooq.shared.internal.VertxPojo;
import io.vertx.core.json.JsonObject;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


import static io.r2mo.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * G_NODE
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public interface IGNode extends VertxPojo, Serializable {

    /**
     * Setter for <code>ZDB.G_NODE.ID</code>. 「id」- 主键
     */
    public IGNode setId(String value);

    /**
     * Getter for <code>ZDB.G_NODE.ID</code>. 「id」- 主键
     */
    public String getId();

    /**
     * Setter for <code>ZDB.G_NODE.GRAPHIC_ID</code>. 「graphicId」 - 它所关联的图实例ID
     */
    public IGNode setGraphicId(String value);

    /**
     * Getter for <code>ZDB.G_NODE.GRAPHIC_ID</code>. 「graphicId」 - 它所关联的图实例ID
     */
    public String getGraphicId();

    /**
     * Setter for <code>ZDB.G_NODE.NAME</code>. 「name」- 名称
     */
    public IGNode setName(String value);

    /**
     * Getter for <code>ZDB.G_NODE.NAME</code>. 「name」- 名称
     */
    public String getName();

    /**
     * Setter for <code>ZDB.G_NODE.RECORD_CLASS</code>. 「recordClass」 -
     * 记录绑定Pojo类型
     */
    public IGNode setRecordClass(String value);

    /**
     * Getter for <code>ZDB.G_NODE.RECORD_CLASS</code>. 「recordClass」 -
     * 记录绑定Pojo类型
     */
    public String getRecordClass();

    /**
     * Setter for <code>ZDB.G_NODE.RECORD_COMPONENT</code>. 「recordComponent」 -
     * 记录处理组件
     */
    public IGNode setRecordComponent(String value);

    /**
     * Getter for <code>ZDB.G_NODE.RECORD_COMPONENT</code>. 「recordComponent」 -
     * 记录处理组件
     */
    public String getRecordComponent();

    /**
     * Setter for <code>ZDB.G_NODE.RECORD_DATA</code>. 「recordData」 - 该节点存储的数据信息
     */
    public IGNode setRecordData(JsonObject value);

    /**
     * Getter for <code>ZDB.G_NODE.RECORD_DATA</code>. 「recordData」 - 该节点存储的数据信息
     */
    public JsonObject getRecordData();

    /**
     * Setter for <code>ZDB.G_NODE.RECORD_KEY</code>. 「recordKey」 - 记录主键
     */
    public IGNode setRecordKey(String value);

    /**
     * Getter for <code>ZDB.G_NODE.RECORD_KEY</code>. 「recordKey」 - 记录主键
     */
    public String getRecordKey();

    /**
     * Setter for <code>ZDB.G_NODE.UI</code>. 「ui」 - ui配置专用
     */
    public IGNode setUi(JsonObject value);

    /**
     * Getter for <code>ZDB.G_NODE.UI</code>. 「ui」 - ui配置专用
     */
    public JsonObject getUi();

    /**
     * Setter for <code>ZDB.G_NODE.X</code>. 「x」 - 当前节点在图上的x坐标
     */
    public IGNode setX(BigDecimal value);

    /**
     * Getter for <code>ZDB.G_NODE.X</code>. 「x」 - 当前节点在图上的x坐标
     */
    public BigDecimal getX();

    /**
     * Setter for <code>ZDB.G_NODE.Y</code>. 「y」 - 当前节点在图上的y坐标
     */
    public IGNode setY(BigDecimal value);

    /**
     * Getter for <code>ZDB.G_NODE.Y</code>. 「y」 - 当前节点在图上的y坐标
     */
    public BigDecimal getY();

    /**
     * Setter for <code>ZDB.G_NODE.SIGMA</code>. 「sigma」- 统一标识
     */
    public IGNode setSigma(String value);

    /**
     * Getter for <code>ZDB.G_NODE.SIGMA</code>. 「sigma」- 统一标识
     */
    public String getSigma();

    /**
     * Setter for <code>ZDB.G_NODE.TENANT_ID</code>. 「tenantId」- 租户ID
     */
    public IGNode setTenantId(String value);

    /**
     * Getter for <code>ZDB.G_NODE.TENANT_ID</code>. 「tenantId」- 租户ID
     */
    public String getTenantId();

    /**
     * Setter for <code>ZDB.G_NODE.APP_ID</code>. 「appId」- 应用ID
     */
    public IGNode setAppId(String value);

    /**
     * Getter for <code>ZDB.G_NODE.APP_ID</code>. 「appId」- 应用ID
     */
    public String getAppId();

    /**
     * Setter for <code>ZDB.G_NODE.ACTIVE</code>. 「active」- 是否启用
     */
    public IGNode setActive(Boolean value);

    /**
     * Getter for <code>ZDB.G_NODE.ACTIVE</code>. 「active」- 是否启用
     */
    public Boolean getActive();

    /**
     * Setter for <code>ZDB.G_NODE.LANGUAGE</code>. 「language」- 语言偏好
     */
    public IGNode setLanguage(String value);

    /**
     * Getter for <code>ZDB.G_NODE.LANGUAGE</code>. 「language」- 语言偏好
     */
    public String getLanguage();

    /**
     * Setter for <code>ZDB.G_NODE.METADATA</code>. 「metadata」- 元配置
     */
    public IGNode setMetadata(JsonObject value);

    /**
     * Getter for <code>ZDB.G_NODE.METADATA</code>. 「metadata」- 元配置
     */
    public JsonObject getMetadata();

    /**
     * Setter for <code>ZDB.G_NODE.VERSION</code>. 「version」- 版本号
     */
    public IGNode setVersion(String value);

    /**
     * Getter for <code>ZDB.G_NODE.VERSION</code>. 「version」- 版本号
     */
    public String getVersion();

    /**
     * Setter for <code>ZDB.G_NODE.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    public IGNode setCreatedAt(LocalDateTime value);

    /**
     * Getter for <code>ZDB.G_NODE.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    public LocalDateTime getCreatedAt();

    /**
     * Setter for <code>ZDB.G_NODE.CREATED_BY</code>. 「createdBy」- 创建人
     */
    public IGNode setCreatedBy(String value);

    /**
     * Getter for <code>ZDB.G_NODE.CREATED_BY</code>. 「createdBy」- 创建人
     */
    public String getCreatedBy();

    /**
     * Setter for <code>ZDB.G_NODE.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    public IGNode setUpdatedAt(LocalDateTime value);

    /**
     * Getter for <code>ZDB.G_NODE.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    public LocalDateTime getUpdatedAt();

    /**
     * Setter for <code>ZDB.G_NODE.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    public IGNode setUpdatedBy(String value);

    /**
     * Getter for <code>ZDB.G_NODE.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    public String getUpdatedBy();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IGNode
     */
    public void from(IGNode from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IGNode
     */
    public <E extends IGNode> E into(E into);

        @Override
        public default IGNode fromJson(io.vertx.core.json.JsonObject json) {
                setOrThrow(this::setId,json::getString,"ID","java.lang.String");
                setOrThrow(this::setGraphicId,json::getString,"GRAPHIC_ID","java.lang.String");
                setOrThrow(this::setName,json::getString,"NAME","java.lang.String");
                setOrThrow(this::setRecordClass,json::getString,"RECORD_CLASS","java.lang.String");
                setOrThrow(this::setRecordComponent,json::getString,"RECORD_COMPONENT","java.lang.String");
                // Omitting unrecognized type io.vertx.core.json.JsonObject for column RECORD_DATA!
                setOrThrow(this::setRecordKey,json::getString,"RECORD_KEY","java.lang.String");
                // Omitting unrecognized type io.vertx.core.json.JsonObject for column UI!
                setOrThrow(this::setX,key -> {String s = json.getString(key); return s==null?null:new java.math.BigDecimal(s);},"X","java.math.BigDecimal");
                setOrThrow(this::setY,key -> {String s = json.getString(key); return s==null?null:new java.math.BigDecimal(s);},"Y","java.math.BigDecimal");
                setOrThrow(this::setSigma,json::getString,"SIGMA","java.lang.String");
                setOrThrow(this::setTenantId,json::getString,"TENANT_ID","java.lang.String");
                setOrThrow(this::setAppId,json::getString,"APP_ID","java.lang.String");
                setOrThrow(this::setActive,json::getBoolean,"ACTIVE","java.lang.Boolean");
                setOrThrow(this::setLanguage,json::getString,"LANGUAGE","java.lang.String");
                // Omitting unrecognized type io.vertx.core.json.JsonObject for column METADATA!
                setOrThrow(this::setVersion,json::getString,"VERSION","java.lang.String");
                setOrThrow(this::setCreatedAt,key -> {String s = json.getString(key); return s==null?null:java.time.LocalDateTime.parse(s);},"CREATED_AT","java.time.LocalDateTime");
                setOrThrow(this::setCreatedBy,json::getString,"CREATED_BY","java.lang.String");
                setOrThrow(this::setUpdatedAt,key -> {String s = json.getString(key); return s==null?null:java.time.LocalDateTime.parse(s);},"UPDATED_AT","java.time.LocalDateTime");
                setOrThrow(this::setUpdatedBy,json::getString,"UPDATED_BY","java.lang.String");
                return this;
        }


        @Override
        public default io.vertx.core.json.JsonObject toJson() {
                io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
                json.put("ID",getId());
                json.put("GRAPHIC_ID",getGraphicId());
                json.put("NAME",getName());
                json.put("RECORD_CLASS",getRecordClass());
                json.put("RECORD_COMPONENT",getRecordComponent());
                // Omitting unrecognized type io.vertx.core.json.JsonObject for column RECORD_DATA!
                json.put("RECORD_KEY",getRecordKey());
                // Omitting unrecognized type io.vertx.core.json.JsonObject for column UI!
                json.put("X",getX()==null?null:getX().toString());
                json.put("Y",getY()==null?null:getY().toString());
                json.put("SIGMA",getSigma());
                json.put("TENANT_ID",getTenantId());
                json.put("APP_ID",getAppId());
                json.put("ACTIVE",getActive());
                json.put("LANGUAGE",getLanguage());
                // Omitting unrecognized type io.vertx.core.json.JsonObject for column METADATA!
                json.put("VERSION",getVersion());
                json.put("CREATED_AT",getCreatedAt()==null?null:getCreatedAt().toString());
                json.put("CREATED_BY",getCreatedBy());
                json.put("UPDATED_AT",getUpdatedAt()==null?null:getUpdatedAt().toString());
                json.put("UPDATED_BY",getUpdatedBy());
                return json;
        }

}
