/*
 * This file is generated by jOOQ.
 */
package io.zerows.extension.module.ui.domain.tables;


import io.zerows.extension.module.ui.domain.Indexes;
import io.zerows.extension.module.ui.domain.Keys;
import io.zerows.extension.module.ui.domain.Zdb;
import io.zerows.extension.module.ui.domain.tables.records.UiPageRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * UI_PAGE
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UiPage extends TableImpl<UiPageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ZDB.UI_PAGE</code>
     */
    public static final UiPage UI_PAGE = new UiPage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UiPageRecord> getRecordType() {
        return UiPageRecord.class;
    }

    /**
     * The column <code>ZDB.UI_PAGE.ID</code>. 「id」- 主键
     */
    public final TableField<UiPageRecord, String> ID = createField(DSL.name("ID"), SQLDataType.VARCHAR(36).nullable(false), this, "「id」- 主键");

    /**
     * The column <code>ZDB.UI_PAGE.APP</code>. 「app」- 入口APP名称
     */
    public final TableField<UiPageRecord, String> APP = createField(DSL.name("APP"), SQLDataType.VARCHAR(32), this, "「app」- 入口APP名称");

    /**
     * The column <code>ZDB.UI_PAGE.ASSIST</code>. 「assist」- 当前页面
     */
    public final TableField<UiPageRecord, String> ASSIST = createField(DSL.name("ASSIST"), SQLDataType.CLOB(65535), this, "「assist」- 当前页面");

    /**
     * The column <code>ZDB.UI_PAGE.CONTAINER_CONFIG</code>. 「containerConfig」-
     * 当前页面容器相关配置
     */
    public final TableField<UiPageRecord, String> CONTAINER_CONFIG = createField(DSL.name("CONTAINER_CONFIG"), SQLDataType.CLOB(65535), this, "「containerConfig」- 当前页面容器相关配置");

    /**
     * The column <code>ZDB.UI_PAGE.CONTAINER_NAME</code>. 「containerName」-
     * 当前页面是否存在容器
     */
    public final TableField<UiPageRecord, String> CONTAINER_NAME = createField(DSL.name("CONTAINER_NAME"), SQLDataType.VARCHAR(32), this, "「containerName」- 当前页面是否存在容器");

    /**
     * The column <code>ZDB.UI_PAGE.GRID</code>. 「grid」- 当前页面的布局信息
     */
    public final TableField<UiPageRecord, String> GRID = createField(DSL.name("GRID"), SQLDataType.CLOB(65535), this, "「grid」- 当前页面的布局信息");

    /**
     * The column <code>ZDB.UI_PAGE.LAYOUT_ID</code>. 「layoutId」- 使用的模板ID
     */
    public final TableField<UiPageRecord, String> LAYOUT_ID = createField(DSL.name("LAYOUT_ID"), SQLDataType.VARCHAR(36), this, "「layoutId」- 使用的模板ID");

    /**
     * The column <code>ZDB.UI_PAGE.MODULE</code>. 「module」- 模块相关信息
     */
    public final TableField<UiPageRecord, String> MODULE = createField(DSL.name("MODULE"), SQLDataType.VARCHAR(32), this, "「module」- 模块相关信息");

    /**
     * The column <code>ZDB.UI_PAGE.PAGE</code>. 「page」- 页面路径信息
     */
    public final TableField<UiPageRecord, String> PAGE = createField(DSL.name("PAGE"), SQLDataType.VARCHAR(32), this, "「page」- 页面路径信息");

    /**
     * The column <code>ZDB.UI_PAGE.PARAM_MAP</code>. 「paramMap」- URL地址中
     */
    public final TableField<UiPageRecord, String> PARAM_MAP = createField(DSL.name("PARAM_MAP"), SQLDataType.CLOB(65535), this, "「paramMap」- URL地址中");

    /**
     * The column <code>ZDB.UI_PAGE.SECURE</code>. 「secure」- 是否执行安全检查
     */
    public final TableField<UiPageRecord, Boolean> SECURE = createField(DSL.name("SECURE"), SQLDataType.BIT, this, "「secure」- 是否执行安全检查");

    /**
     * The column <code>ZDB.UI_PAGE.STATE</code>. 「state」- 当前页面
     */
    public final TableField<UiPageRecord, String> STATE = createField(DSL.name("STATE"), SQLDataType.CLOB(65535), this, "「state」- 当前页面");

    /**
     * The column <code>ZDB.UI_PAGE.SIGMA</code>. 「sigma」- 统一标识
     */
    public final TableField<UiPageRecord, String> SIGMA = createField(DSL.name("SIGMA"), SQLDataType.VARCHAR(128), this, "「sigma」- 统一标识");

    /**
     * The column <code>ZDB.UI_PAGE.TENANT_ID</code>. 「tenantId」- 租户ID
     */
    public final TableField<UiPageRecord, String> TENANT_ID = createField(DSL.name("TENANT_ID"), SQLDataType.VARCHAR(36), this, "「tenantId」- 租户ID");

    /**
     * The column <code>ZDB.UI_PAGE.APP_ID</code>. 「appId」- 应用ID
     */
    public final TableField<UiPageRecord, String> APP_ID = createField(DSL.name("APP_ID"), SQLDataType.VARCHAR(36), this, "「appId」- 应用ID");

    /**
     * The column <code>ZDB.UI_PAGE.ACTIVE</code>. 「active」- 是否启用
     */
    public final TableField<UiPageRecord, Boolean> ACTIVE = createField(DSL.name("ACTIVE"), SQLDataType.BIT, this, "「active」- 是否启用");

    /**
     * The column <code>ZDB.UI_PAGE.LANGUAGE</code>. 「language」- 语言偏好
     */
    public final TableField<UiPageRecord, String> LANGUAGE = createField(DSL.name("LANGUAGE"), SQLDataType.VARCHAR(10), this, "「language」- 语言偏好");

    /**
     * The column <code>ZDB.UI_PAGE.METADATA</code>. 「metadata」- 元配置
     */
    public final TableField<UiPageRecord, String> METADATA = createField(DSL.name("METADATA"), SQLDataType.CLOB(65535), this, "「metadata」- 元配置");

    /**
     * The column <code>ZDB.UI_PAGE.VERSION</code>. 「version」- 版本号
     */
    public final TableField<UiPageRecord, String> VERSION = createField(DSL.name("VERSION"), SQLDataType.VARCHAR(64), this, "「version」- 版本号");

    /**
     * The column <code>ZDB.UI_PAGE.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    public final TableField<UiPageRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(0), this, "「createdAt」- 创建时间");

    /**
     * The column <code>ZDB.UI_PAGE.CREATED_BY</code>. 「createdBy」- 创建人
     */
    public final TableField<UiPageRecord, String> CREATED_BY = createField(DSL.name("CREATED_BY"), SQLDataType.VARCHAR(36), this, "「createdBy」- 创建人");

    /**
     * The column <code>ZDB.UI_PAGE.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    public final TableField<UiPageRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(0), this, "「updatedAt」- 更新时间");

    /**
     * The column <code>ZDB.UI_PAGE.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    public final TableField<UiPageRecord, String> UPDATED_BY = createField(DSL.name("UPDATED_BY"), SQLDataType.VARCHAR(36), this, "「updatedBy」- 更新人");

    private UiPage(Name alias, Table<UiPageRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UiPage(Name alias, Table<UiPageRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("UI_PAGE"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>ZDB.UI_PAGE</code> table reference
     */
    public UiPage(String alias) {
        this(DSL.name(alias), UI_PAGE);
    }

    /**
     * Create an aliased <code>ZDB.UI_PAGE</code> table reference
     */
    public UiPage(Name alias) {
        this(alias, UI_PAGE);
    }

    /**
     * Create a <code>ZDB.UI_PAGE</code> table reference
     */
    public UiPage() {
        this(DSL.name("UI_PAGE"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Zdb.ZDB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.UI_PAGE_IDXM_UI_PAGE_APP_MODULE_PAGE_LANGUAGE_SIGMA);
    }

    @Override
    public UniqueKey<UiPageRecord> getPrimaryKey() {
        return Keys.KEY_UI_PAGE_PRIMARY;
    }

    @Override
    public List<UniqueKey<UiPageRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_UI_PAGE_UK_UI_PAGE_APP_MODULE_PAGE_SIGMA);
    }

    @Override
    public UiPage as(String alias) {
        return new UiPage(DSL.name(alias), this);
    }

    @Override
    public UiPage as(Name alias) {
        return new UiPage(alias, this);
    }

    @Override
    public UiPage as(Table<?> alias) {
        return new UiPage(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UiPage rename(String name) {
        return new UiPage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UiPage rename(Name name) {
        return new UiPage(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UiPage rename(Table<?> name) {
        return new UiPage(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UiPage where(Condition condition) {
        return new UiPage(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UiPage where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UiPage where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UiPage where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UiPage where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UiPage where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UiPage where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UiPage where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UiPage whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UiPage whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
