/*
 * This file is generated by jOOQ.
 */
package io.zerows.extension.module.finance.domain.tables.records;


import io.r2mo.vertx.jooq.shared.internal.VertxPojo;
import io.zerows.extension.module.finance.domain.tables.FBank;
import io.zerows.extension.module.finance.domain.tables.interfaces.IFBank;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class FBankRecord extends UpdatableRecordImpl<FBankRecord> implements VertxPojo, IFBank {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached FBankRecord
     */
    public FBankRecord() {
        super(FBank.F_BANK);
    }

    /**
     * Create a detached, initialised FBankRecord
     */
    public FBankRecord(String key, String name, String code, String alias, String logo, String website, String comment, String branchName, String branchCode, Boolean branch, String bankId, String locationId, String sigma, String language, Boolean active, String metadata, LocalDateTime createdAt, String createdBy, LocalDateTime updatedAt, String updatedBy, String appId, String tenantId) {
        super(FBank.F_BANK);

        setKey(key);
        setName(name);
        setCode(code);
        setAlias(alias);
        setLogo(logo);
        setWebsite(website);
        setComment(comment);
        setBranchName(branchName);
        setBranchCode(branchCode);
        setBranch(branch);
        setBankId(bankId);
        setLocationId(locationId);
        setSigma(sigma);
        setLanguage(language);
        setActive(active);
        setMetadata(metadata);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
        setAppId(appId);
        setTenantId(tenantId);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised FBankRecord
     */
    public FBankRecord(IFBank value) {
        super(FBank.F_BANK);

        if (value != null) {
            setKey(value.getKey());
            setName(value.getName());
            setCode(value.getCode());
            setAlias(value.getAlias());
            setLogo(value.getLogo());
            setWebsite(value.getWebsite());
            setComment(value.getComment());
            setBranchName(value.getBranchName());
            setBranchCode(value.getBranchCode());
            setBranch(value.getBranch());
            setBankId(value.getBankId());
            setLocationId(value.getLocationId());
            setSigma(value.getSigma());
            setLanguage(value.getLanguage());
            setActive(value.getActive());
            setMetadata(value.getMetadata());
            setCreatedAt(value.getCreatedAt());
            setCreatedBy(value.getCreatedBy());
            setUpdatedAt(value.getUpdatedAt());
            setUpdatedBy(value.getUpdatedBy());
            setAppId(value.getAppId());
            setTenantId(value.getTenantId());
            resetTouchedOnNotNull();
        }
    }

    public FBankRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    /**
     * Getter for <code>ZDB.F_BANK.KEY</code>. 「key」- 银行主键
     */
    @Override
    public String getKey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>ZDB.F_BANK.KEY</code>. 「key」- 银行主键
     */
    @Override
    public FBankRecord setKey(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.F_BANK.NAME</code>. 「name」- 银行名称
     */
    @Override
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ZDB.F_BANK.NAME</code>. 「name」- 银行名称
     */
    @Override
    public FBankRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.F_BANK.CODE</code>. 「code」- 银行系统编号
     */
    @Override
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ZDB.F_BANK.CODE</code>. 「code」- 银行系统编号
     */
    @Override
    public FBankRecord setCode(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.F_BANK.ALIAS</code>. 「alias」- 银行别称
     */
    @Override
    public String getAlias() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ZDB.F_BANK.ALIAS</code>. 「alias」- 银行别称
     */
    @Override
    public FBankRecord setAlias(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.F_BANK.LOGO</code>. 「logo」- 银行图标
     */
    @Override
    public String getLogo() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ZDB.F_BANK.LOGO</code>. 「logo」- 银行图标
     */
    @Override
    public FBankRecord setLogo(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.F_BANK.WEBSITE</code>. 「website」- 银行主页
     */
    @Override
    public String getWebsite() {
        return (String) get(5);
    }

    /**
     * Setter for <code>ZDB.F_BANK.WEBSITE</code>. 「website」- 银行主页
     */
    @Override
    public FBankRecord setWebsite(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.F_BANK.COMMENT</code>. 「comment」 - 银行备注
     */
    @Override
    public String getComment() {
        return (String) get(6);
    }

    /**
     * Setter for <code>ZDB.F_BANK.COMMENT</code>. 「comment」 - 银行备注
     */
    @Override
    public FBankRecord setComment(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.F_BANK.BRANCH_NAME</code>. 「branchName」- 支行名称
     */
    @Override
    public String getBranchName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>ZDB.F_BANK.BRANCH_NAME</code>. 「branchName」- 支行名称
     */
    @Override
    public FBankRecord setBranchName(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.F_BANK.BRANCH_CODE</code>. 「branchCode」- 支行编号
     */
    @Override
    public String getBranchCode() {
        return (String) get(8);
    }

    /**
     * Setter for <code>ZDB.F_BANK.BRANCH_CODE</code>. 「branchCode」- 支行编号
     */
    @Override
    public FBankRecord setBranchCode(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.F_BANK.BRANCH</code>. 「branch」- 是否支行
     */
    @Override
    public Boolean getBranch() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>ZDB.F_BANK.BRANCH</code>. 「branch」- 是否支行
     */
    @Override
    public FBankRecord setBranch(Boolean value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.F_BANK.BANK_ID</code>. 「bankId」- 所属银行ID
     */
    @Override
    public String getBankId() {
        return (String) get(10);
    }

    /**
     * Setter for <code>ZDB.F_BANK.BANK_ID</code>. 「bankId」- 所属银行ID
     */
    @Override
    public FBankRecord setBankId(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.F_BANK.LOCATION_ID</code>. 「locationId」- 银行地址对应信息
     */
    @Override
    public String getLocationId() {
        return (String) get(11);
    }

    /**
     * Setter for <code>ZDB.F_BANK.LOCATION_ID</code>. 「locationId」- 银行地址对应信息
     */
    @Override
    public FBankRecord setLocationId(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.F_BANK.SIGMA</code>. 「sigma」- 用户组绑定的统一标识
     */
    @Override
    public String getSigma() {
        return (String) get(12);
    }

    /**
     * Setter for <code>ZDB.F_BANK.SIGMA</code>. 「sigma」- 用户组绑定的统一标识
     */
    @Override
    public FBankRecord setSigma(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.F_BANK.LANGUAGE</code>. 「language」- 使用的语言
     */
    @Override
    public String getLanguage() {
        return (String) get(13);
    }

    /**
     * Setter for <code>ZDB.F_BANK.LANGUAGE</code>. 「language」- 使用的语言
     */
    @Override
    public FBankRecord setLanguage(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.F_BANK.ACTIVE</code>. 「active」- 是否启用
     */
    @Override
    public Boolean getActive() {
        return (Boolean) get(14);
    }

    /**
     * Setter for <code>ZDB.F_BANK.ACTIVE</code>. 「active」- 是否启用
     */
    @Override
    public FBankRecord setActive(Boolean value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.F_BANK.METADATA</code>. 「metadata」- 附加配置数据
     */
    @Override
    public String getMetadata() {
        return (String) get(15);
    }

    /**
     * Setter for <code>ZDB.F_BANK.METADATA</code>. 「metadata」- 附加配置数据
     */
    @Override
    public FBankRecord setMetadata(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.F_BANK.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    @Override
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(16);
    }

    /**
     * Setter for <code>ZDB.F_BANK.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    @Override
    public FBankRecord setCreatedAt(LocalDateTime value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.F_BANK.CREATED_BY</code>. 「createdBy」- 创建人
     */
    @Override
    public String getCreatedBy() {
        return (String) get(17);
    }

    /**
     * Setter for <code>ZDB.F_BANK.CREATED_BY</code>. 「createdBy」- 创建人
     */
    @Override
    public FBankRecord setCreatedBy(String value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.F_BANK.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    @Override
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(18);
    }

    /**
     * Setter for <code>ZDB.F_BANK.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    @Override
    public FBankRecord setUpdatedAt(LocalDateTime value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.F_BANK.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    @Override
    public String getUpdatedBy() {
        return (String) get(19);
    }

    /**
     * Setter for <code>ZDB.F_BANK.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    @Override
    public FBankRecord setUpdatedBy(String value) {
        set(19, value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>ZDB.F_BANK.APP_ID</code>. 「appId」- 应用ID
     */
    @Override
    public String getAppId() {
        return (String) get(20);
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>ZDB.F_BANK.APP_ID</code>. 「appId」- 应用ID
     */
    @Override
    public FBankRecord setAppId(String value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.F_BANK.TENANT_ID</code>. 「tenantId」- 租户ID
     */
    @Override
    public String getTenantId() {
        return (String) get(21);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>ZDB.F_BANK.TENANT_ID</code>. 「tenantId」- 租户ID
     */
    @Override
    public FBankRecord setTenantId(String value) {
        set(21, value);
        return this;
    }

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    @Override
    public void from(IFBank from) {
        setKey(from.getKey());
        setName(from.getName());
        setCode(from.getCode());
        setAlias(from.getAlias());
        setLogo(from.getLogo());
        setWebsite(from.getWebsite());
        setComment(from.getComment());
        setBranchName(from.getBranchName());
        setBranchCode(from.getBranchCode());
        setBranch(from.getBranch());
        setBankId(from.getBankId());
        setLocationId(from.getLocationId());
        setSigma(from.getSigma());
        setLanguage(from.getLanguage());
        setActive(from.getActive());
        setMetadata(from.getMetadata());
        setCreatedAt(from.getCreatedAt());
        setCreatedBy(from.getCreatedBy());
        setUpdatedAt(from.getUpdatedAt());
        setUpdatedBy(from.getUpdatedBy());
        setAppId(from.getAppId());
        setTenantId(from.getTenantId());
        resetTouchedOnNotNull();
    }

    @Override
    public <E extends IFBank> E into(E into) {
        into.from(this);
        return into;
    }
}
