-- ============================================================
-- OAuth2 数据库结构（大写命名版，兼容 MySQL 5.7+ / 8.0+）
-- 使用存储过程方式安全删除索引（避免语法错误）
-- ============================================================

SET NAMES utf8mb4;

-- =========================
-- 1. 注册客户端表
-- =========================

-- 删除表（安全）
DROP TABLE IF EXISTS OAUTH2_REGISTERED_CLIENT;

CREATE TABLE OAUTH2_REGISTERED_CLIENT
(
    ID                            VARCHAR(100)  NOT NULL COMMENT '主键 ID（内部标识）',
    CLIENT_ID                     VARCHAR(100)  NOT NULL COMMENT '客户端 ID',
    CLIENT_ID_ISSUED_AT           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '客户端 ID 签发时间',
    CLIENT_SECRET                 VARCHAR(200) NULL COMMENT '客户端密钥（可为空，例如 public client）',
    CLIENT_SECRET_EXPIRES_AT      TIMESTAMP NULL COMMENT '客户端密钥过期时间',
    CLIENT_NAME                   VARCHAR(200)  NOT NULL COMMENT '客户端显示名称',
    CLIENT_AUTHENTICATION_METHODS VARCHAR(1000) NOT NULL COMMENT '客户端认证方式，逗号分隔',
    AUTHORIZATION_GRANT_TYPES     VARCHAR(1000) NOT NULL COMMENT '授权类型，逗号分隔',
    REDIRECT_URIS                 VARCHAR(2000) NULL COMMENT '授权回调地址列表，逗号分隔',
    POST_LOGOUT_REDIRECT_URIS     VARCHAR(2000) NULL COMMENT '登出回调地址列表，逗号分隔',
    SCOPES                        VARCHAR(1000) NOT NULL COMMENT 'Scope 列表，逗号分隔',
    CLIENT_SETTINGS               LONGTEXT COMMENT 'Client 级别设置（JSON 字符串）',
    TOKEN_SETTINGS                LONGTEXT COMMENT 'Token 级别设置（JSON 字符串）',
    TENANT_ID                     VARCHAR(64) NULL COMMENT '租户 ID（多租户场景可用）',
    APP_ID                        VARCHAR(64) NULL COMMENT '应用 ID（多应用场景可用）',
    EXT                           LONGTEXT NULL COMMENT '扩展字段（业务自定义）',
    CONSTRAINT PK_OAUTH2_REGISTERED_CLIENT PRIMARY KEY (ID),
    CONSTRAINT UK_OAUTH2_REGISTERED_CLIENT_CLIENT_ID UNIQUE (CLIENT_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci COMMENT = 'OAuth2 注册客户端表';

-- 安全创建索引：先删除（如果存在），再创建
DELIMITER;;
DROP PROCEDURE IF EXISTS DROP_INDEX_IF_EXISTS;;
CREATE PROCEDURE DROP_INDEX_IF_EXISTS()
BEGIN
    IF
(
SELECT COUNT(*)
FROM information_schema.statistics
WHERE table_schema = DATABASE()
  AND table_name = 'OAUTH2_REGISTERED_CLIENT'
  AND index_name = 'IDX_OAUTH2_REGISTERED_CLIENT_TENANT') > 0
    THEN
SET @SQL_STMT = 'DROP INDEX IDX_OAUTH2_REGISTERED_CLIENT_TENANT ON OAUTH2_REGISTERED_CLIENT';
PREPARE STMT FROM @SQL_STMT;
EXECUTE STMT;
DEALLOCATE PREPARE STMT;
END IF;
END;;
DELIMITER ;

CALL DROP_INDEX_IF_EXISTS();
DROP PROCEDURE DROP_INDEX_IF_EXISTS;

CREATE INDEX IDX_OAUTH2_REGISTERED_CLIENT_TENANT ON OAUTH2_REGISTERED_CLIENT (TENANT_ID);


-- =========================
-- 2. 授权 / Token 信息表
-- =========================

DROP TABLE IF EXISTS OAUTH2_AUTHORIZATION;

CREATE TABLE OAUTH2_AUTHORIZATION
(
    ID                            VARCHAR(100) NOT NULL COMMENT '主键 ID',
    REGISTERED_CLIENT_ID          VARCHAR(100) NOT NULL COMMENT '关联客户端 ID（OAUTH2_REGISTERED_CLIENT.ID）',
    PRINCIPAL_NAME                VARCHAR(200) NOT NULL COMMENT '主体名称（通常为用户名 / userId）',
    AUTHORIZATION_GRANT_TYPE      VARCHAR(100) NOT NULL COMMENT '授权类型',
    AUTHORIZED_SCOPES             VARCHAR(1000) NULL COMMENT '授权范围（Scope 列表）',
    ATTRIBUTES                    TEXT NULL COMMENT '附加属性（JSON 字符串）',
    STATE                         VARCHAR(500) NULL COMMENT 'state 参数值',
    AUTHORIZATION_CODE_VALUE      LONGTEXT NULL COMMENT '授权码值',
    AUTHORIZATION_CODE_ISSUED_AT  TIMESTAMP NULL COMMENT '授权码签发时间',
    AUTHORIZATION_CODE_EXPIRES_AT TIMESTAMP NULL COMMENT '授权码过期时间',
    AUTHORIZATION_CODE_METADATA   TEXT NULL COMMENT '授权码元数据（JSON 字符串）',
    ACCESS_TOKEN_VALUE            LONGTEXT NULL COMMENT '访问令牌值',
    ACCESS_TOKEN_ISSUED_AT        TIMESTAMP NULL COMMENT '访问令牌签发时间',
    ACCESS_TOKEN_EXPIRES_AT       TIMESTAMP NULL COMMENT '访问令牌过期时间',
    ACCESS_TOKEN_METADATA         TEXT NULL COMMENT '访问令牌元数据（JSON 字符串）',
    ACCESS_TOKEN_TYPE             VARCHAR(100) NULL COMMENT '访问令牌类型（如 Bearer）',
    ACCESS_TOKEN_SCOPES           VARCHAR(1000) NULL COMMENT '访问令牌 Scope 列表',
    OIDC_ID_TOKEN_VALUE           LONGTEXT NULL COMMENT 'ID Token 值',
    OIDC_ID_TOKEN_ISSUED_AT       TIMESTAMP NULL COMMENT 'ID Token 签发时间',
    OIDC_ID_TOKEN_EXPIRES_AT      TIMESTAMP NULL COMMENT 'ID Token 过期时间',
    OIDC_ID_TOKEN_METADATA        TEXT NULL COMMENT 'ID Token 元数据（JSON 字符串）',
    OIDC_ID_TOKEN_CLAIMS          TEXT NULL COMMENT 'ID Token Claims（JSON 字符串）',
    REFRESH_TOKEN_VALUE           LONGTEXT NULL COMMENT '刷新令牌值',
    REFRESH_TOKEN_ISSUED_AT       TIMESTAMP NULL COMMENT '刷新令牌签发时间',
    REFRESH_TOKEN_EXPIRES_AT      TIMESTAMP NULL COMMENT '刷新令牌过期时间',
    REFRESH_TOKEN_METADATA        TEXT NULL COMMENT '刷新令牌元数据（JSON 字符串）',
    USER_CODE_VALUE               LONGTEXT NULL COMMENT 'User Code 值',
    USER_CODE_ISSUED_AT           TIMESTAMP NULL COMMENT 'User Code 签发时间',
    USER_CODE_EXPIRES_AT          TIMESTAMP NULL COMMENT 'User Code 过期时间',
    USER_CODE_METADATA            TEXT NULL COMMENT 'User Code 元数据（JSON 字符串）',
    DEVICE_CODE_VALUE             LONGTEXT NULL COMMENT 'Device Code 值',
    DEVICE_CODE_ISSUED_AT         TIMESTAMP NULL COMMENT 'Device Code 签发时间',
    DEVICE_CODE_EXPIRES_AT        TIMESTAMP NULL COMMENT 'Device Code 过期时间',
    DEVICE_CODE_METADATA          TEXT NULL COMMENT 'Device Code 元数据（JSON 字符串）',
    TENANT_ID                     VARCHAR(64) NULL COMMENT '租户 ID（可选）',
    APP_ID                        VARCHAR(64) NULL COMMENT '应用 ID（多应用场景可用）',
    EXT                           JSON NULL COMMENT '扩展字段（业务自定义）',
    CONSTRAINT PK_OAUTH2_AUTHORIZATION PRIMARY KEY (ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci COMMENT = 'OAuth2 授权与 Token 信息表';

-- 辅助过程：删除指定索引（如果存在）
DELIMITER;;
DROP PROCEDURE IF EXISTS DROP_AUTHZ_INDEX;;
CREATE PROCEDURE DROP_AUTHZ_INDEX(IN IDX_NAME VARCHAR (128))
BEGIN
    IF
(
SELECT COUNT(*)
FROM information_schema.statistics
WHERE table_schema = DATABASE()
  AND table_name = 'OAUTH2_AUTHORIZATION'
  AND index_name = IDX_NAME) > 0
    THEN
SET @SQL_STMT = CONCAT('DROP INDEX ', IDX_NAME, ' ON OAUTH2_AUTHORIZATION');
PREPARE STMT FROM @SQL_STMT;
EXECUTE STMT;
DEALLOCATE PREPARE STMT;
END IF;
END;;
DELIMITER ;

CALL DROP_AUTHZ_INDEX('IDX_OAUTH2_AUTHORIZATION_CLIENT_PRINCIPAL');
CALL DROP_AUTHZ_INDEX('IDX_OAUTH2_AUTHORIZATION_GRANT_TYPE');
CALL DROP_AUTHZ_INDEX('IDX_OAUTH2_AUTHORIZATION_PRINCIPAL');
CALL DROP_AUTHZ_INDEX('IDX_OAUTH2_AUTHORIZATION_TENANT');
DROP PROCEDURE DROP_AUTHZ_INDEX;

CREATE INDEX IDX_OAUTH2_AUTHORIZATION_CLIENT_PRINCIPAL ON OAUTH2_AUTHORIZATION (REGISTERED_CLIENT_ID, PRINCIPAL_NAME);
CREATE INDEX IDX_OAUTH2_AUTHORIZATION_GRANT_TYPE ON OAUTH2_AUTHORIZATION (AUTHORIZATION_GRANT_TYPE);
CREATE INDEX IDX_OAUTH2_AUTHORIZATION_PRINCIPAL ON OAUTH2_AUTHORIZATION (PRINCIPAL_NAME);
CREATE INDEX IDX_OAUTH2_AUTHORIZATION_TENANT ON OAUTH2_AUTHORIZATION (TENANT_ID);


-- =========================
-- 3. 授权同意（Consent）表
-- =========================

DROP TABLE IF EXISTS OAUTH2_AUTHORIZATION_CONSENT;

CREATE TABLE OAUTH2_AUTHORIZATION_CONSENT
(
    REGISTERED_CLIENT_ID VARCHAR(100)  NOT NULL COMMENT '客户端 ID（OAUTH2_REGISTERED_CLIENT.ID）',
    PRINCIPAL_NAME       VARCHAR(200)  NOT NULL COMMENT '主体名称（用户名 / userId）',
    AUTHORITIES          VARCHAR(1000) NOT NULL COMMENT '已同意的权限集合（逗号分隔）',
    TENANT_ID            VARCHAR(64) NULL COMMENT '租户 ID（可选）',
    APP_ID               VARCHAR(64) NULL COMMENT '应用 ID（多应用场景可用）',
    EXT                  JSON NULL COMMENT '扩展字段（业务自定义）',
    CONSTRAINT PK_OAUTH2_AUTHORIZATION_CONSENT PRIMARY KEY (REGISTERED_CLIENT_ID, PRINCIPAL_NAME)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci COMMENT = 'OAuth2 授权同意（Consent）记录表';

DELIMITER;;
DROP PROCEDURE IF EXISTS DROP_CONSENT_INDEX;;
CREATE PROCEDURE DROP_CONSENT_INDEX(IN IDX_NAME VARCHAR (128))
BEGIN
    IF
(
SELECT COUNT(*)
FROM information_schema.statistics
WHERE table_schema = DATABASE()
  AND table_name = 'OAUTH2_AUTHORIZATION_CONSENT'
  AND index_name = IDX_NAME) > 0
    THEN
SET @SQL_STMT = CONCAT('DROP INDEX ', IDX_NAME, ' ON OAUTH2_AUTHORIZATION_CONSENT');
PREPARE STMT FROM @SQL_STMT;
EXECUTE STMT;
DEALLOCATE PREPARE STMT;
END IF;
END;;
DELIMITER ;

CALL DROP_CONSENT_INDEX('IDX_OAUTH2_AUTHORIZATION_CONSENT_PRINCIPAL');
CALL DROP_CONSENT_INDEX('IDX_OAUTH2_AUTHORIZATION_CONSENT_TENANT');
DROP PROCEDURE DROP_CONSENT_INDEX;

CREATE INDEX IDX_OAUTH2_AUTHORIZATION_CONSENT_PRINCIPAL ON OAUTH2_AUTHORIZATION_CONSENT (PRINCIPAL_NAME);
CREATE INDEX IDX_OAUTH2_AUTHORIZATION_CONSENT_TENANT ON OAUTH2_AUTHORIZATION_CONSENT (TENANT_ID);