/*
 * This file is generated by jOOQ.
 */
package io.zerows.extension.module.rbac.domain.tables.records;


import io.r2mo.vertx.jooq.shared.internal.VertxPojo;
import io.zerows.extension.module.rbac.domain.tables.RRolePerm;
import io.zerows.extension.module.rbac.domain.tables.interfaces.IRRolePerm;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class RRolePermRecord extends UpdatableRecordImpl<RRolePermRecord> implements VertxPojo, IRRolePerm {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached RRolePermRecord
     */
    public RRolePermRecord() {
        super(RRolePerm.R_ROLE_PERM);
    }

    /**
     * Create a detached, initialised RRolePermRecord
     */
    public RRolePermRecord(String permId, String roleId) {
        super(RRolePerm.R_ROLE_PERM);

        setPermId(permId);
        setRoleId(roleId);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised RRolePermRecord
     */
    public RRolePermRecord(IRRolePerm value) {
        super(RRolePerm.R_ROLE_PERM);

        if (value != null) {
            setPermId(value.getPermId());
            setRoleId(value.getRoleId());
            resetTouchedOnNotNull();
        }
    }

    public RRolePermRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>ZDB.R_ROLE_PERM.PERM_ID</code>. 「permId」- 关联权限ID
     */
    @Override
    public String getPermId() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>ZDB.R_ROLE_PERM.PERM_ID</code>. 「permId」- 关联权限ID
     */
    @Override
    public RRolePermRecord setPermId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.R_ROLE_PERM.ROLE_ID</code>. 「roleId」- 关联角色ID
     */
    @Override
    public String getRoleId() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>ZDB.R_ROLE_PERM.ROLE_ID</code>. 「roleId」- 关联角色ID
     */
    @Override
    public RRolePermRecord setRoleId(String value) {
        set(1, value);
        return this;
    }

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    @Override
    public void from(IRRolePerm from) {
        setPermId(from.getPermId());
        setRoleId(from.getRoleId());
        resetTouchedOnNotNull();
    }

    @Override
    public <E extends IRRolePerm> E into(E into) {
        into.from(this);
        return into;
    }
}
