/*
 * This file is generated by jOOQ.
 */
package io.zerows.extension.module.ambient.domain.tables.records;


import io.r2mo.vertx.jooq.shared.internal.VertxPojo;
import io.zerows.extension.module.ambient.domain.tables.XApp;
import io.zerows.extension.module.ambient.domain.tables.interfaces.IXApp;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


import static io.r2mo.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * X_APP
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class XAppRecord extends UpdatableRecordImpl<XAppRecord> implements VertxPojo, IXApp {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ZDB.X_APP.ID</code>. 「id」- 主键
     */
    @Override
    public XAppRecord setId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.X_APP.ID</code>. 「id」- 主键
     */
    @Override
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>ZDB.X_APP.APP_KEY</code>. 「appKey」- 敏感标识符
     */
    @Override
    public XAppRecord setAppKey(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.X_APP.APP_KEY</code>. 「appKey」- 敏感标识符
     */
    @Override
    public String getAppKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ZDB.X_APP.APP_SECRET</code>. 「appSecret」- 应用密钥
     */
    @Override
    public XAppRecord setAppSecret(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.X_APP.APP_SECRET</code>. 「appSecret」- 应用密钥
     */
    @Override
    public String getAppSecret() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ZDB.X_APP.CODE</code>. 「code」- 编号
     */
    @Override
    public XAppRecord setCode(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.X_APP.CODE</code>. 「code」- 编号
     */
    @Override
    public String getCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ZDB.X_APP.CONTEXT</code>. 「configure」- 应用路径
     */
    @Override
    public XAppRecord setContext(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.X_APP.CONTEXT</code>. 「configure」- 应用路径
     */
    @Override
    public String getContext() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ZDB.X_APP.COPY_RIGHT</code>. 「copyRight」- 版权
     */
    @Override
    public XAppRecord setCopyRight(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.X_APP.COPY_RIGHT</code>. 「copyRight」- 版权
     */
    @Override
    public String getCopyRight() {
        return (String) get(5);
    }

    /**
     * Setter for <code>ZDB.X_APP.DOMAIN</code>. 「domain」- 服务器域
     */
    @Override
    public XAppRecord setDomain(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.X_APP.DOMAIN</code>. 「domain」- 服务器域
     */
    @Override
    public String getDomain() {
        return (String) get(6);
    }

    /**
     * Setter for <code>ZDB.X_APP.EMAIL</code>. 「email」- 管理员Email
     */
    @Override
    public XAppRecord setEmail(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.X_APP.EMAIL</code>. 「email」- 管理员Email
     */
    @Override
    public String getEmail() {
        return (String) get(7);
    }

    /**
     * Setter for <code>ZDB.X_APP.ENDPOINT</code>. 「endpoint」- Web服务端地址
     */
    @Override
    public XAppRecord setEndpoint(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.X_APP.ENDPOINT</code>. 「endpoint」- Web服务端地址
     */
    @Override
    public String getEndpoint() {
        return (String) get(8);
    }

    /**
     * Setter for <code>ZDB.X_APP.ENTRY</code>. 「entry」- 入口菜单
     */
    @Override
    public XAppRecord setEntry(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.X_APP.ENTRY</code>. 「entry」- 入口菜单
     */
    @Override
    public String getEntry() {
        return (String) get(9);
    }

    /**
     * Setter for <code>ZDB.X_APP.ICP</code>. 「icp」- ICP备案号
     */
    @Override
    public XAppRecord setIcp(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.X_APP.ICP</code>. 「icp」- ICP备案号
     */
    @Override
    public String getIcp() {
        return (String) get(10);
    }

    /**
     * Setter for <code>ZDB.X_APP.LOGO</code>. 「logo」- 图标
     */
    @Override
    public XAppRecord setLogo(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.X_APP.LOGO</code>. 「logo」- 图标
     */
    @Override
    public String getLogo() {
        return (String) get(11);
    }

    /**
     * Setter for <code>ZDB.X_APP.NAME</code>. 「name」- 名称
     */
    @Override
    public XAppRecord setName(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.X_APP.NAME</code>. 「name」- 名称
     */
    @Override
    public String getName() {
        return (String) get(12);
    }

    /**
     * Setter for <code>ZDB.X_APP.PORT</code>. 「port」- 端口号
     */
    @Override
    public XAppRecord setPort(Integer value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.X_APP.PORT</code>. 「port」- 端口号
     */
    @Override
    public Integer getPort() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>ZDB.X_APP.TITLE</code>. 「title」- 应用标题
     */
    @Override
    public XAppRecord setTitle(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.X_APP.TITLE</code>. 「title」- 应用标题
     */
    @Override
    public String getTitle() {
        return (String) get(14);
    }

    /**
     * Setter for <code>ZDB.X_APP.URL_ADMIN</code>. 「urlAdmin」- 管理业URL
     */
    @Override
    public XAppRecord setUrlAdmin(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.X_APP.URL_ADMIN</code>. 「urlAdmin」- 管理业URL
     */
    @Override
    public String getUrlAdmin() {
        return (String) get(15);
    }

    /**
     * Setter for <code>ZDB.X_APP.URL_LOGIN</code>. 「urlLogin」— 登录页URL
     */
    @Override
    public XAppRecord setUrlLogin(String value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.X_APP.URL_LOGIN</code>. 「urlLogin」— 登录页URL
     */
    @Override
    public String getUrlLogin() {
        return (String) get(16);
    }

    /**
     * Setter for <code>ZDB.X_APP.STATUS</code>. 「status」- 状态
     */
    @Override
    public XAppRecord setStatus(String value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.X_APP.STATUS</code>. 「status」- 状态
     */
    @Override
    public String getStatus() {
        return (String) get(17);
    }

    /**
     * Setter for <code>ZDB.X_APP.SIGMA</code>. 「sigma」- 统一标识
     */
    @Override
    public XAppRecord setSigma(String value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.X_APP.SIGMA</code>. 「sigma」- 统一标识
     */
    @Override
    public String getSigma() {
        return (String) get(18);
    }

    /**
     * Setter for <code>ZDB.X_APP.TENANT_ID</code>. 「tenantId」- 租户ID
     */
    @Override
    public XAppRecord setTenantId(String value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.X_APP.TENANT_ID</code>. 「tenantId」- 租户ID
     */
    @Override
    public String getTenantId() {
        return (String) get(19);
    }

    /**
     * Setter for <code>ZDB.X_APP.APP_ID</code>. 「appId」- 父应用ID
     */
    @Override
    public XAppRecord setAppId(String value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.X_APP.APP_ID</code>. 「appId」- 父应用ID
     */
    @Override
    public String getAppId() {
        return (String) get(20);
    }

    /**
     * Setter for <code>ZDB.X_APP.ACTIVE</code>. 「active」- 是否启用
     */
    @Override
    public XAppRecord setActive(Boolean value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.X_APP.ACTIVE</code>. 「active」- 是否启用
     */
    @Override
    public Boolean getActive() {
        return (Boolean) get(21);
    }

    /**
     * Setter for <code>ZDB.X_APP.LANGUAGE</code>. 「language」- 语言偏好
     */
    @Override
    public XAppRecord setLanguage(String value) {
        set(22, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.X_APP.LANGUAGE</code>. 「language」- 语言偏好
     */
    @Override
    public String getLanguage() {
        return (String) get(22);
    }

    /**
     * Setter for <code>ZDB.X_APP.METADATA</code>. 「metadata」- 元配置
     */
    @Override
    public XAppRecord setMetadata(String value) {
        set(23, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.X_APP.METADATA</code>. 「metadata」- 元配置
     */
    @Override
    public String getMetadata() {
        return (String) get(23);
    }

    /**
     * Setter for <code>ZDB.X_APP.VERSION</code>. 「version」- 版本号
     */
    @Override
    public XAppRecord setVersion(String value) {
        set(24, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.X_APP.VERSION</code>. 「version」- 版本号
     */
    @Override
    public String getVersion() {
        return (String) get(24);
    }

    /**
     * Setter for <code>ZDB.X_APP.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    @Override
    public XAppRecord setCreatedAt(LocalDateTime value) {
        set(25, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.X_APP.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    @Override
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(25);
    }

    /**
     * Setter for <code>ZDB.X_APP.CREATED_BY</code>. 「createdBy」- 创建人
     */
    @Override
    public XAppRecord setCreatedBy(String value) {
        set(26, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.X_APP.CREATED_BY</code>. 「createdBy」- 创建人
     */
    @Override
    public String getCreatedBy() {
        return (String) get(26);
    }

    /**
     * Setter for <code>ZDB.X_APP.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    @Override
    public XAppRecord setUpdatedAt(LocalDateTime value) {
        set(27, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.X_APP.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    @Override
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(27);
    }

    /**
     * Setter for <code>ZDB.X_APP.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    @Override
    public XAppRecord setUpdatedBy(String value) {
        set(28, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.X_APP.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    @Override
    public String getUpdatedBy() {
        return (String) get(28);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IXApp from) {
        setId(from.getId());
        setAppKey(from.getAppKey());
        setAppSecret(from.getAppSecret());
        setCode(from.getCode());
        setContext(from.getContext());
        setCopyRight(from.getCopyRight());
        setDomain(from.getDomain());
        setEmail(from.getEmail());
        setEndpoint(from.getEndpoint());
        setEntry(from.getEntry());
        setIcp(from.getIcp());
        setLogo(from.getLogo());
        setName(from.getName());
        setPort(from.getPort());
        setTitle(from.getTitle());
        setUrlAdmin(from.getUrlAdmin());
        setUrlLogin(from.getUrlLogin());
        setStatus(from.getStatus());
        setSigma(from.getSigma());
        setTenantId(from.getTenantId());
        setAppId(from.getAppId());
        setActive(from.getActive());
        setLanguage(from.getLanguage());
        setMetadata(from.getMetadata());
        setVersion(from.getVersion());
        setCreatedAt(from.getCreatedAt());
        setCreatedBy(from.getCreatedBy());
        setUpdatedAt(from.getUpdatedAt());
        setUpdatedBy(from.getUpdatedBy());
        resetTouchedOnNotNull();
    }

    @Override
    public <E extends IXApp> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached XAppRecord
     */
    public XAppRecord() {
        super(XApp.X_APP);
    }

    /**
     * Create a detached, initialised XAppRecord
     */
    public XAppRecord(String id, String appKey, String appSecret, String code, String context, String copyRight, String domain, String email, String endpoint, String entry, String icp, String logo, String name, Integer port, String title, String urlAdmin, String urlLogin, String status, String sigma, String tenantId, String appId, Boolean active, String language, String metadata, String version, LocalDateTime createdAt, String createdBy, LocalDateTime updatedAt, String updatedBy) {
        super(XApp.X_APP);

        setId(id);
        setAppKey(appKey);
        setAppSecret(appSecret);
        setCode(code);
        setContext(context);
        setCopyRight(copyRight);
        setDomain(domain);
        setEmail(email);
        setEndpoint(endpoint);
        setEntry(entry);
        setIcp(icp);
        setLogo(logo);
        setName(name);
        setPort(port);
        setTitle(title);
        setUrlAdmin(urlAdmin);
        setUrlLogin(urlLogin);
        setStatus(status);
        setSigma(sigma);
        setTenantId(tenantId);
        setAppId(appId);
        setActive(active);
        setLanguage(language);
        setMetadata(metadata);
        setVersion(version);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised XAppRecord
     */
    public XAppRecord(IXApp value) {
        super(XApp.X_APP);

        if (value != null) {
            setId(value.getId());
            setAppKey(value.getAppKey());
            setAppSecret(value.getAppSecret());
            setCode(value.getCode());
            setContext(value.getContext());
            setCopyRight(value.getCopyRight());
            setDomain(value.getDomain());
            setEmail(value.getEmail());
            setEndpoint(value.getEndpoint());
            setEntry(value.getEntry());
            setIcp(value.getIcp());
            setLogo(value.getLogo());
            setName(value.getName());
            setPort(value.getPort());
            setTitle(value.getTitle());
            setUrlAdmin(value.getUrlAdmin());
            setUrlLogin(value.getUrlLogin());
            setStatus(value.getStatus());
            setSigma(value.getSigma());
            setTenantId(value.getTenantId());
            setAppId(value.getAppId());
            setActive(value.getActive());
            setLanguage(value.getLanguage());
            setMetadata(value.getMetadata());
            setVersion(value.getVersion());
            setCreatedAt(value.getCreatedAt());
            setCreatedBy(value.getCreatedBy());
            setUpdatedAt(value.getUpdatedAt());
            setUpdatedBy(value.getUpdatedBy());
            resetTouchedOnNotNull();
        }
    }

        public XAppRecord(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }
}
