/*
 * This file is generated by jOOQ.
 */
package io.zerows.extension.module.integration.domain.tables.records;


import io.r2mo.vertx.jooq.shared.internal.VertxPojo;
import io.zerows.extension.module.integration.domain.tables.IMessage;
import io.zerows.extension.module.integration.domain.tables.interfaces.IIMessage;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


import static io.r2mo.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IMessageRecord extends UpdatableRecordImpl<IMessageRecord> implements VertxPojo, IIMessage {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ZDB.I_MESSAGE.KEY</code>. 「key」- 消息主键
     */
    @Override
    public IMessageRecord setKey(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.I_MESSAGE.KEY</code>. 「key」- 消息主键
     */
    @Override
    public String getKey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>ZDB.I_MESSAGE.NAME</code>. 「name」- 消息名称
     */
    @Override
    public IMessageRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.I_MESSAGE.NAME</code>. 「name」- 消息名称
     */
    @Override
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ZDB.I_MESSAGE.CODE</code>. 「code」- 消息编码
     */
    @Override
    public IMessageRecord setCode(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.I_MESSAGE.CODE</code>. 「code」- 消息编码
     */
    @Override
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ZDB.I_MESSAGE.TYPE</code>. 「type」- 消息类型
     */
    @Override
    public IMessageRecord setType(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.I_MESSAGE.TYPE</code>. 「type」- 消息类型
     */
    @Override
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ZDB.I_MESSAGE.STATUS</code>. 「status」- 消息状态
     */
    @Override
    public IMessageRecord setStatus(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.I_MESSAGE.STATUS</code>. 「status」- 消息状态
     */
    @Override
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ZDB.I_MESSAGE.SUBJECT</code>. 「subject」- 消息标题
     */
    @Override
    public IMessageRecord setSubject(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.I_MESSAGE.SUBJECT</code>. 「subject」- 消息标题
     */
    @Override
    public String getSubject() {
        return (String) get(5);
    }

    /**
     * Setter for <code>ZDB.I_MESSAGE.CONTENT</code>. 「content」- 消息内容
     */
    @Override
    public IMessageRecord setContent(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.I_MESSAGE.CONTENT</code>. 「content」- 消息内容
     */
    @Override
    public String getContent() {
        return (String) get(6);
    }

    /**
     * Setter for <code>ZDB.I_MESSAGE.SEND_FROM</code>. 「from」- 消息发送方
     */
    @Override
    public IMessageRecord setSendFrom(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.I_MESSAGE.SEND_FROM</code>. 「from」- 消息发送方
     */
    @Override
    public String getSendFrom() {
        return (String) get(7);
    }

    /**
     * Setter for <code>ZDB.I_MESSAGE.SEND_TO</code>. 「to」- 消息接收方
     */
    @Override
    public IMessageRecord setSendTo(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.I_MESSAGE.SEND_TO</code>. 「to」- 消息接收方
     */
    @Override
    public String getSendTo() {
        return (String) get(8);
    }

    /**
     * Setter for <code>ZDB.I_MESSAGE.SEND_BY</code>. 「sendBy」- 发送者
     */
    @Override
    public IMessageRecord setSendBy(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.I_MESSAGE.SEND_BY</code>. 「sendBy」- 发送者
     */
    @Override
    public String getSendBy() {
        return (String) get(9);
    }

    /**
     * Setter for <code>ZDB.I_MESSAGE.SEND_AT</code>. 「sendAt」- 发送时间
     */
    @Override
    public IMessageRecord setSendAt(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.I_MESSAGE.SEND_AT</code>. 「sendAt」- 发送时间
     */
    @Override
    public String getSendAt() {
        return (String) get(10);
    }

    /**
     * Setter for <code>ZDB.I_MESSAGE.SIGMA</code>. 「sigma」- 用户组绑定的统一标识
     */
    @Override
    public IMessageRecord setSigma(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.I_MESSAGE.SIGMA</code>. 「sigma」- 用户组绑定的统一标识
     */
    @Override
    public String getSigma() {
        return (String) get(11);
    }

    /**
     * Setter for <code>ZDB.I_MESSAGE.LANGUAGE</code>. 「language」- 使用的语言
     */
    @Override
    public IMessageRecord setLanguage(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.I_MESSAGE.LANGUAGE</code>. 「language」- 使用的语言
     */
    @Override
    public String getLanguage() {
        return (String) get(12);
    }

    /**
     * Setter for <code>ZDB.I_MESSAGE.ACTIVE</code>. 「active」- 是否启用
     */
    @Override
    public IMessageRecord setActive(Boolean value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.I_MESSAGE.ACTIVE</code>. 「active」- 是否启用
     */
    @Override
    public Boolean getActive() {
        return (Boolean) get(13);
    }

    /**
     * Setter for <code>ZDB.I_MESSAGE.METADATA</code>. 「metadata」- 附加配置数据
     */
    @Override
    public IMessageRecord setMetadata(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.I_MESSAGE.METADATA</code>. 「metadata」- 附加配置数据
     */
    @Override
    public String getMetadata() {
        return (String) get(14);
    }

    /**
     * Setter for <code>ZDB.I_MESSAGE.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    @Override
    public IMessageRecord setCreatedAt(LocalDateTime value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.I_MESSAGE.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    @Override
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>ZDB.I_MESSAGE.CREATED_BY</code>. 「createdBy」- 创建人
     */
    @Override
    public IMessageRecord setCreatedBy(String value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.I_MESSAGE.CREATED_BY</code>. 「createdBy」- 创建人
     */
    @Override
    public String getCreatedBy() {
        return (String) get(16);
    }

    /**
     * Setter for <code>ZDB.I_MESSAGE.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    @Override
    public IMessageRecord setUpdatedAt(LocalDateTime value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.I_MESSAGE.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    @Override
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(17);
    }

    /**
     * Setter for <code>ZDB.I_MESSAGE.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    @Override
    public IMessageRecord setUpdatedBy(String value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.I_MESSAGE.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    @Override
    public String getUpdatedBy() {
        return (String) get(18);
    }

    /**
     * Setter for <code>ZDB.I_MESSAGE.APP_ID</code>. 「appId」- 应用ID
     */
    @Override
    public IMessageRecord setAppId(String value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.I_MESSAGE.APP_ID</code>. 「appId」- 应用ID
     */
    @Override
    public String getAppId() {
        return (String) get(19);
    }

    /**
     * Setter for <code>ZDB.I_MESSAGE.TENANT_ID</code>. 「tenantId」- 租户ID
     */
    @Override
    public IMessageRecord setTenantId(String value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.I_MESSAGE.TENANT_ID</code>. 「tenantId」- 租户ID
     */
    @Override
    public String getTenantId() {
        return (String) get(20);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IIMessage from) {
        setKey(from.getKey());
        setName(from.getName());
        setCode(from.getCode());
        setType(from.getType());
        setStatus(from.getStatus());
        setSubject(from.getSubject());
        setContent(from.getContent());
        setSendFrom(from.getSendFrom());
        setSendTo(from.getSendTo());
        setSendBy(from.getSendBy());
        setSendAt(from.getSendAt());
        setSigma(from.getSigma());
        setLanguage(from.getLanguage());
        setActive(from.getActive());
        setMetadata(from.getMetadata());
        setCreatedAt(from.getCreatedAt());
        setCreatedBy(from.getCreatedBy());
        setUpdatedAt(from.getUpdatedAt());
        setUpdatedBy(from.getUpdatedBy());
        setAppId(from.getAppId());
        setTenantId(from.getTenantId());
        resetTouchedOnNotNull();
    }

    @Override
    public <E extends IIMessage> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IMessageRecord
     */
    public IMessageRecord() {
        super(IMessage.I_MESSAGE);
    }

    /**
     * Create a detached, initialised IMessageRecord
     */
    public IMessageRecord(String key, String name, String code, String type, String status, String subject, String content, String sendFrom, String sendTo, String sendBy, String sendAt, String sigma, String language, Boolean active, String metadata, LocalDateTime createdAt, String createdBy, LocalDateTime updatedAt, String updatedBy, String appId, String tenantId) {
        super(IMessage.I_MESSAGE);

        setKey(key);
        setName(name);
        setCode(code);
        setType(type);
        setStatus(status);
        setSubject(subject);
        setContent(content);
        setSendFrom(sendFrom);
        setSendTo(sendTo);
        setSendBy(sendBy);
        setSendAt(sendAt);
        setSigma(sigma);
        setLanguage(language);
        setActive(active);
        setMetadata(metadata);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
        setAppId(appId);
        setTenantId(tenantId);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised IMessageRecord
     */
    public IMessageRecord(IIMessage value) {
        super(IMessage.I_MESSAGE);

        if (value != null) {
            setKey(value.getKey());
            setName(value.getName());
            setCode(value.getCode());
            setType(value.getType());
            setStatus(value.getStatus());
            setSubject(value.getSubject());
            setContent(value.getContent());
            setSendFrom(value.getSendFrom());
            setSendTo(value.getSendTo());
            setSendBy(value.getSendBy());
            setSendAt(value.getSendAt());
            setSigma(value.getSigma());
            setLanguage(value.getLanguage());
            setActive(value.getActive());
            setMetadata(value.getMetadata());
            setCreatedAt(value.getCreatedAt());
            setCreatedBy(value.getCreatedBy());
            setUpdatedAt(value.getUpdatedAt());
            setUpdatedBy(value.getUpdatedBy());
            setAppId(value.getAppId());
            setTenantId(value.getTenantId());
            resetTouchedOnNotNull();
        }
    }

        public IMessageRecord(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }
}
