/*
 * This file is generated by jOOQ.
 */
package io.zerows.extension.module.finance.domain.tables;


import io.zerows.extension.module.finance.domain.Keys;
import io.zerows.extension.module.finance.domain.Zdb;
import io.zerows.extension.module.finance.domain.tables.records.FSubjectRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * F_SUBJECT
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FSubject extends TableImpl<FSubjectRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ZDB.F_SUBJECT</code>
     */
    public static final FSubject F_SUBJECT = new FSubject();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FSubjectRecord> getRecordType() {
        return FSubjectRecord.class;
    }

    /**
     * The column <code>ZDB.F_SUBJECT.ID</code>. 「id」- 主键
     */
    public final TableField<FSubjectRecord, String> ID = createField(DSL.name("ID"), SQLDataType.VARCHAR(36).nullable(false), this, "「id」- 主键");

    /**
     * The column <code>ZDB.F_SUBJECT.CODE</code>. 「code」- 编号
     */
    public final TableField<FSubjectRecord, String> CODE = createField(DSL.name("CODE"), SQLDataType.VARCHAR(255), this, "「code」- 编号");

    /**
     * The column <code>ZDB.F_SUBJECT.COMMENT</code>. 「comment」- 备注
     */
    public final TableField<FSubjectRecord, String> COMMENT = createField(DSL.name("COMMENT"), SQLDataType.CLOB, this, "「comment」- 备注");

    /**
     * The column <code>ZDB.F_SUBJECT.COMPANY_ID</code>. 「companyId」 - 会计科目所属公司
     */
    public final TableField<FSubjectRecord, String> COMPANY_ID = createField(DSL.name("COMPANY_ID"), SQLDataType.VARCHAR(36), this, "「companyId」 - 会计科目所属公司");

    /**
     * The column <code>ZDB.F_SUBJECT.HELP_CODE</code>. 「helpCode」 - 会计科目助记码
     */
    public final TableField<FSubjectRecord, String> HELP_CODE = createField(DSL.name("HELP_CODE"), SQLDataType.VARCHAR(32), this, "「helpCode」 - 会计科目助记码");

    /**
     * The column <code>ZDB.F_SUBJECT.NAME</code>. 「name」- 名称
     */
    public final TableField<FSubjectRecord, String> NAME = createField(DSL.name("NAME"), SQLDataType.VARCHAR(255).nullable(false), this, "「name」- 名称");

    /**
     * The column <code>ZDB.F_SUBJECT.OWNER</code>. 「owner」 - 科目方向：OUT-借方 /
     * IN-贷方
     */
    public final TableField<FSubjectRecord, String> OWNER = createField(DSL.name("OWNER"), SQLDataType.VARCHAR(32), this, "「owner」 - 科目方向：OUT-借方 / IN-贷方");

    /**
     * The column <code>ZDB.F_SUBJECT.PARENT_ID</code>. 「parentId」- 父节点
     */
    public final TableField<FSubjectRecord, String> PARENT_ID = createField(DSL.name("PARENT_ID"), SQLDataType.VARCHAR(36), this, "「parentId」- 父节点");

    /**
     * The column <code>ZDB.F_SUBJECT.SERIAL</code>. 「serial」- 单号
     */
    public final TableField<FSubjectRecord, String> SERIAL = createField(DSL.name("SERIAL"), SQLDataType.VARCHAR(128), this, "「serial」- 单号");

    /**
     * The column <code>ZDB.F_SUBJECT.CATEGORY</code>. 「category」- 类别
     */
    public final TableField<FSubjectRecord, String> CATEGORY = createField(DSL.name("CATEGORY"), SQLDataType.VARCHAR(36), this, "「category」- 类别");

    /**
     * The column <code>ZDB.F_SUBJECT.SIGMA</code>. 「sigma」- 统一标识
     */
    public final TableField<FSubjectRecord, String> SIGMA = createField(DSL.name("SIGMA"), SQLDataType.VARCHAR(128), this, "「sigma」- 统一标识");

    /**
     * The column <code>ZDB.F_SUBJECT.TENANT_ID</code>. 「tenantId」- 租户ID
     */
    public final TableField<FSubjectRecord, String> TENANT_ID = createField(DSL.name("TENANT_ID"), SQLDataType.VARCHAR(36), this, "「tenantId」- 租户ID");

    /**
     * The column <code>ZDB.F_SUBJECT.APP_ID</code>. 「appId」- 应用ID
     */
    public final TableField<FSubjectRecord, String> APP_ID = createField(DSL.name("APP_ID"), SQLDataType.VARCHAR(36), this, "「appId」- 应用ID");

    /**
     * The column <code>ZDB.F_SUBJECT.ACTIVE</code>. 「active」- 是否启用
     */
    public final TableField<FSubjectRecord, Boolean> ACTIVE = createField(DSL.name("ACTIVE"), SQLDataType.BIT, this, "「active」- 是否启用");

    /**
     * The column <code>ZDB.F_SUBJECT.LANGUAGE</code>. 「language」- 语言偏好
     */
    public final TableField<FSubjectRecord, String> LANGUAGE = createField(DSL.name("LANGUAGE"), SQLDataType.VARCHAR(10), this, "「language」- 语言偏好");

    /**
     * The column <code>ZDB.F_SUBJECT.METADATA</code>. 「metadata」- 元配置
     */
    public final TableField<FSubjectRecord, String> METADATA = createField(DSL.name("METADATA"), SQLDataType.CLOB(65535), this, "「metadata」- 元配置");

    /**
     * The column <code>ZDB.F_SUBJECT.VERSION</code>. 「version」- 版本号
     */
    public final TableField<FSubjectRecord, String> VERSION = createField(DSL.name("VERSION"), SQLDataType.VARCHAR(64), this, "「version」- 版本号");

    /**
     * The column <code>ZDB.F_SUBJECT.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    public final TableField<FSubjectRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(0), this, "「createdAt」- 创建时间");

    /**
     * The column <code>ZDB.F_SUBJECT.CREATED_BY</code>. 「createdBy」- 创建人
     */
    public final TableField<FSubjectRecord, String> CREATED_BY = createField(DSL.name("CREATED_BY"), SQLDataType.VARCHAR(36), this, "「createdBy」- 创建人");

    /**
     * The column <code>ZDB.F_SUBJECT.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    public final TableField<FSubjectRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(0), this, "「updatedAt」- 更新时间");

    /**
     * The column <code>ZDB.F_SUBJECT.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    public final TableField<FSubjectRecord, String> UPDATED_BY = createField(DSL.name("UPDATED_BY"), SQLDataType.VARCHAR(36), this, "「updatedBy」- 更新人");

    private FSubject(Name alias, Table<FSubjectRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private FSubject(Name alias, Table<FSubjectRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("F_SUBJECT"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>ZDB.F_SUBJECT</code> table reference
     */
    public FSubject(String alias) {
        this(DSL.name(alias), F_SUBJECT);
    }

    /**
     * Create an aliased <code>ZDB.F_SUBJECT</code> table reference
     */
    public FSubject(Name alias) {
        this(alias, F_SUBJECT);
    }

    /**
     * Create a <code>ZDB.F_SUBJECT</code> table reference
     */
    public FSubject() {
        this(DSL.name("F_SUBJECT"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Zdb.ZDB;
    }

    @Override
    public UniqueKey<FSubjectRecord> getPrimaryKey() {
        return Keys.KEY_F_SUBJECT_PRIMARY;
    }

    @Override
    public List<UniqueKey<FSubjectRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_F_SUBJECT_UK_F_SUBJECT_CODE_SIGMA);
    }

    @Override
    public FSubject as(String alias) {
        return new FSubject(DSL.name(alias), this);
    }

    @Override
    public FSubject as(Name alias) {
        return new FSubject(alias, this);
    }

    @Override
    public FSubject as(Table<?> alias) {
        return new FSubject(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FSubject rename(String name) {
        return new FSubject(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FSubject rename(Name name) {
        return new FSubject(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FSubject rename(Table<?> name) {
        return new FSubject(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FSubject where(Condition condition) {
        return new FSubject(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FSubject where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FSubject where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FSubject where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FSubject where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FSubject where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FSubject where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FSubject where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FSubject whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FSubject whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
