/*
 * This file is generated by jOOQ.
 */
package io.zerows.extension.module.erp.domain.tables.records;


import io.r2mo.vertx.jooq.shared.internal.VertxPojo;
import io.zerows.extension.module.erp.domain.tables.TVendorCheckOut;
import io.zerows.extension.module.erp.domain.tables.interfaces.ITVendorCheckOut;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


import static io.r2mo.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * 供应商 - 离场登记
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TVendorCheckOutRecord extends UpdatableRecordImpl<TVendorCheckOutRecord> implements VertxPojo, ITVendorCheckOut {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ZDB.T_VENDOR_CHECK_OUT.ID</code>. 「id」- 主键
     */
    @Override
    public TVendorCheckOutRecord setId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.T_VENDOR_CHECK_OUT.ID</code>. 「id」- 主键
     */
    @Override
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>ZDB.T_VENDOR_CHECK_OUT.CLASSIFICATION</code>.
     * 「classification」- 退场类型
     */
    @Override
    public TVendorCheckOutRecord setClassification(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.T_VENDOR_CHECK_OUT.CLASSIFICATION</code>.
     * 「classification」- 退场类型
     */
    @Override
    public String getClassification() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ZDB.T_VENDOR_CHECK_OUT.LEAVE_AT</code>. 「leaveAt」- 离场时间
     */
    @Override
    public TVendorCheckOutRecord setLeaveAt(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.T_VENDOR_CHECK_OUT.LEAVE_AT</code>. 「leaveAt」- 离场时间
     */
    @Override
    public LocalDateTime getLeaveAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>ZDB.T_VENDOR_CHECK_OUT.REASON</code>. 「reason」- 原因
     */
    @Override
    public TVendorCheckOutRecord setReason(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.T_VENDOR_CHECK_OUT.REASON</code>. 「reason」- 原因
     */
    @Override
    public String getReason() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ZDB.T_VENDOR_CHECK_OUT.START_AT</code>. 「startAt」- 开始时间
     */
    @Override
    public TVendorCheckOutRecord setStartAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.T_VENDOR_CHECK_OUT.START_AT</code>. 「startAt」- 开始时间
     */
    @Override
    public LocalDateTime getStartAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>ZDB.T_VENDOR_CHECK_OUT.END_AT</code>. 「endAt」- 结束时间
     */
    @Override
    public TVendorCheckOutRecord setEndAt(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.T_VENDOR_CHECK_OUT.END_AT</code>. 「endAt」- 结束时间
     */
    @Override
    public LocalDateTime getEndAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>ZDB.T_VENDOR_CHECK_OUT.DAYS</code>. 「days」- 持续天数
     */
    @Override
    public TVendorCheckOutRecord setDays(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.T_VENDOR_CHECK_OUT.DAYS</code>. 「days」- 持续天数
     */
    @Override
    public Integer getDays() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>ZDB.T_VENDOR_CHECK_OUT.COMMENT_EXTENSION</code>.
     * 「commentExtension」- 扩展备注
     */
    @Override
    public TVendorCheckOutRecord setCommentExtension(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.T_VENDOR_CHECK_OUT.COMMENT_EXTENSION</code>.
     * 「commentExtension」- 扩展备注
     */
    @Override
    public String getCommentExtension() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ITVendorCheckOut from) {
        setId(from.getId());
        setClassification(from.getClassification());
        setLeaveAt(from.getLeaveAt());
        setReason(from.getReason());
        setStartAt(from.getStartAt());
        setEndAt(from.getEndAt());
        setDays(from.getDays());
        setCommentExtension(from.getCommentExtension());
        resetTouchedOnNotNull();
    }

    @Override
    public <E extends ITVendorCheckOut> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TVendorCheckOutRecord
     */
    public TVendorCheckOutRecord() {
        super(TVendorCheckOut.T_VENDOR_CHECK_OUT);
    }

    /**
     * Create a detached, initialised TVendorCheckOutRecord
     */
    public TVendorCheckOutRecord(String id, String classification, LocalDateTime leaveAt, String reason, LocalDateTime startAt, LocalDateTime endAt, Integer days, String commentExtension) {
        super(TVendorCheckOut.T_VENDOR_CHECK_OUT);

        setId(id);
        setClassification(classification);
        setLeaveAt(leaveAt);
        setReason(reason);
        setStartAt(startAt);
        setEndAt(endAt);
        setDays(days);
        setCommentExtension(commentExtension);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised TVendorCheckOutRecord
     */
    public TVendorCheckOutRecord(ITVendorCheckOut value) {
        super(TVendorCheckOut.T_VENDOR_CHECK_OUT);

        if (value != null) {
            setId(value.getId());
            setClassification(value.getClassification());
            setLeaveAt(value.getLeaveAt());
            setReason(value.getReason());
            setStartAt(value.getStartAt());
            setEndAt(value.getEndAt());
            setDays(value.getDays());
            setCommentExtension(value.getCommentExtension());
            resetTouchedOnNotNull();
        }
    }

        public TVendorCheckOutRecord(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }
}
