package io.zerows.plugins.security.weco;

interface ApiAddr {

    String PREFIX = "Ἀτλαντὶς νῆσος://Ασφάλεια/";
    String API_AUTH_WECOM_INIT = PREFIX + "AUTH-WECOM-INIT";
    String API_AUTH_WECOM_LOGIN = PREFIX + "AUTH-WECOM-LOGIN";
    String API_AUTH_WECOM_QRCODE = PREFIX + "AUTH-WECOM-QRCODE";

    String API_AUTH_WEMP_QRCODE = PREFIX + "AUTH-WEMP-QRCODE";
    String API_AUTH_WEMP_STATUS = PREFIX + "AUTH-WEMP-STATUS";
    String API_AUTH_WEMP_CALLBACK_GET = PREFIX + "AUTH-WEMP-CALLBACK-GET";
    String API_AUTH_WEMP_CALLBACK_POST = PREFIX + "AUTH-WEMP-CALLBACK-POST";
}
