/*
 * This file is generated by jOOQ.
 */
package io.zerows.extension.module.modulat.domain.tables.records;


import io.r2mo.vertx.jooq.shared.internal.VertxPojo;
import io.zerows.extension.module.modulat.domain.tables.BComponent;
import io.zerows.extension.module.modulat.domain.tables.interfaces.IBComponent;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


import static io.r2mo.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BComponentRecord extends UpdatableRecordImpl<BComponentRecord> implements VertxPojo, IBComponent {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ZDB.B_COMPONENT.KEY</code>. 「key」- 主键
     */
    @Override
    public BComponentRecord setKey(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.B_COMPONENT.KEY</code>. 「key」- 主键
     */
    @Override
    public String getKey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>ZDB.B_COMPONENT.BLOCK_ID</code>. 「blockId」- 所属模块ID
     */
    @Override
    public BComponentRecord setBlockId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.B_COMPONENT.BLOCK_ID</code>. 「blockId」- 所属模块ID
     */
    @Override
    public String getBlockId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ZDB.B_COMPONENT.TYPE</code>. 「type」- 类型保留，单独区分
     */
    @Override
    public BComponentRecord setType(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.B_COMPONENT.TYPE</code>. 「type」- 类型保留，单独区分
     */
    @Override
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ZDB.B_COMPONENT.MAVEN_AID</code>. 「mavenAid」- 所在项目ID
     */
    @Override
    public BComponentRecord setMavenAid(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.B_COMPONENT.MAVEN_AID</code>. 「mavenAid」- 所在项目ID
     */
    @Override
    public String getMavenAid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ZDB.B_COMPONENT.MAVEN_GID</code>. 「mavenGid」- 所在Group的ID
     */
    @Override
    public BComponentRecord setMavenGid(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.B_COMPONENT.MAVEN_GID</code>. 「mavenGid」- 所在Group的ID
     */
    @Override
    public String getMavenGid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ZDB.B_COMPONENT.SPEC_INTERFACE</code>. 「specInterface」-
     * 接口名称
     */
    @Override
    public BComponentRecord setSpecInterface(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.B_COMPONENT.SPEC_INTERFACE</code>. 「specInterface」-
     * 接口名称
     */
    @Override
    public String getSpecInterface() {
        return (String) get(5);
    }

    /**
     * Setter for <code>ZDB.B_COMPONENT.SPEC_IMPL</code>. 「specImpl」- 实现组件
     */
    @Override
    public BComponentRecord setSpecImpl(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.B_COMPONENT.SPEC_IMPL</code>. 「specImpl」- 实现组件
     */
    @Override
    public String getSpecImpl() {
        return (String) get(6);
    }

    /**
     * Setter for <code>ZDB.B_COMPONENT.INTEGRATED</code>. 「integrated」-
     * 是否用于外部集成
     */
    @Override
    public BComponentRecord setIntegrated(Boolean value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.B_COMPONENT.INTEGRATED</code>. 「integrated」-
     * 是否用于外部集成
     */
    @Override
    public Boolean getIntegrated() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>ZDB.B_COMPONENT.SIGMA</code>. 「sigma」- 用户组绑定的统一标识
     */
    @Override
    public BComponentRecord setSigma(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.B_COMPONENT.SIGMA</code>. 「sigma」- 用户组绑定的统一标识
     */
    @Override
    public String getSigma() {
        return (String) get(8);
    }

    /**
     * Setter for <code>ZDB.B_COMPONENT.LANGUAGE</code>. 「language」- 使用的语言
     */
    @Override
    public BComponentRecord setLanguage(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.B_COMPONENT.LANGUAGE</code>. 「language」- 使用的语言
     */
    @Override
    public String getLanguage() {
        return (String) get(9);
    }

    /**
     * Setter for <code>ZDB.B_COMPONENT.ACTIVE</code>. 「active」- 是否启用
     */
    @Override
    public BComponentRecord setActive(Boolean value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.B_COMPONENT.ACTIVE</code>. 「active」- 是否启用
     */
    @Override
    public Boolean getActive() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>ZDB.B_COMPONENT.METADATA</code>. 「metadata」- 附加配置数据
     */
    @Override
    public BComponentRecord setMetadata(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.B_COMPONENT.METADATA</code>. 「metadata」- 附加配置数据
     */
    @Override
    public String getMetadata() {
        return (String) get(11);
    }

    /**
     * Setter for <code>ZDB.B_COMPONENT.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    @Override
    public BComponentRecord setCreatedAt(LocalDateTime value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.B_COMPONENT.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    @Override
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>ZDB.B_COMPONENT.CREATED_BY</code>. 「createdBy」- 创建人
     */
    @Override
    public BComponentRecord setCreatedBy(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.B_COMPONENT.CREATED_BY</code>. 「createdBy」- 创建人
     */
    @Override
    public String getCreatedBy() {
        return (String) get(13);
    }

    /**
     * Setter for <code>ZDB.B_COMPONENT.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    @Override
    public BComponentRecord setUpdatedAt(LocalDateTime value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.B_COMPONENT.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    @Override
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>ZDB.B_COMPONENT.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    @Override
    public BComponentRecord setUpdatedBy(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.B_COMPONENT.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    @Override
    public String getUpdatedBy() {
        return (String) get(15);
    }

    /**
     * Setter for <code>ZDB.B_COMPONENT.APP_ID</code>. 「appId」- 应用ID
     */
    @Override
    public BComponentRecord setAppId(String value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.B_COMPONENT.APP_ID</code>. 「appId」- 应用ID
     */
    @Override
    public String getAppId() {
        return (String) get(16);
    }

    /**
     * Setter for <code>ZDB.B_COMPONENT.TENANT_ID</code>. 「tenantId」- 租户ID
     */
    @Override
    public BComponentRecord setTenantId(String value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>ZDB.B_COMPONENT.TENANT_ID</code>. 「tenantId」- 租户ID
     */
    @Override
    public String getTenantId() {
        return (String) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IBComponent from) {
        setKey(from.getKey());
        setBlockId(from.getBlockId());
        setType(from.getType());
        setMavenAid(from.getMavenAid());
        setMavenGid(from.getMavenGid());
        setSpecInterface(from.getSpecInterface());
        setSpecImpl(from.getSpecImpl());
        setIntegrated(from.getIntegrated());
        setSigma(from.getSigma());
        setLanguage(from.getLanguage());
        setActive(from.getActive());
        setMetadata(from.getMetadata());
        setCreatedAt(from.getCreatedAt());
        setCreatedBy(from.getCreatedBy());
        setUpdatedAt(from.getUpdatedAt());
        setUpdatedBy(from.getUpdatedBy());
        setAppId(from.getAppId());
        setTenantId(from.getTenantId());
        resetTouchedOnNotNull();
    }

    @Override
    public <E extends IBComponent> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BComponentRecord
     */
    public BComponentRecord() {
        super(BComponent.B_COMPONENT);
    }

    /**
     * Create a detached, initialised BComponentRecord
     */
    public BComponentRecord(String key, String blockId, String type, String mavenAid, String mavenGid, String specInterface, String specImpl, Boolean integrated, String sigma, String language, Boolean active, String metadata, LocalDateTime createdAt, String createdBy, LocalDateTime updatedAt, String updatedBy, String appId, String tenantId) {
        super(BComponent.B_COMPONENT);

        setKey(key);
        setBlockId(blockId);
        setType(type);
        setMavenAid(mavenAid);
        setMavenGid(mavenGid);
        setSpecInterface(specInterface);
        setSpecImpl(specImpl);
        setIntegrated(integrated);
        setSigma(sigma);
        setLanguage(language);
        setActive(active);
        setMetadata(metadata);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
        setAppId(appId);
        setTenantId(tenantId);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised BComponentRecord
     */
    public BComponentRecord(IBComponent value) {
        super(BComponent.B_COMPONENT);

        if (value != null) {
            setKey(value.getKey());
            setBlockId(value.getBlockId());
            setType(value.getType());
            setMavenAid(value.getMavenAid());
            setMavenGid(value.getMavenGid());
            setSpecInterface(value.getSpecInterface());
            setSpecImpl(value.getSpecImpl());
            setIntegrated(value.getIntegrated());
            setSigma(value.getSigma());
            setLanguage(value.getLanguage());
            setActive(value.getActive());
            setMetadata(value.getMetadata());
            setCreatedAt(value.getCreatedAt());
            setCreatedBy(value.getCreatedBy());
            setUpdatedAt(value.getUpdatedAt());
            setUpdatedBy(value.getUpdatedBy());
            setAppId(value.getAppId());
            setTenantId(value.getTenantId());
            resetTouchedOnNotNull();
        }
    }

        public BComponentRecord(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }
}
