/*
 * This file is generated by jOOQ.
 */
package io.zerows.extension.module.rbac.domain.tables.pojos;


import io.r2mo.vertx.jooq.shared.internal.VertxPojo;
import io.zerows.extension.module.rbac.domain.tables.interfaces.IOUser;

import java.time.LocalDateTime;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class OUser implements VertxPojo, IOUser {

    private static final long serialVersionUID = 1L;

    private String key;
    private String redirectUri;
    private String code;
    private String clientSecret;
    private String clientId;
    private String grantType;
    private String scope;
    private String state;
    private String sigma;
    private String language;
    private Boolean active;
    private String metadata;
    private LocalDateTime createdAt;
    private String createdBy;
    private LocalDateTime updatedAt;
    private String updatedBy;
    private String appId;
    private String tenantId;

    public OUser() {
    }

    public OUser(IOUser value) {
        this.key = value.getKey();
        this.redirectUri = value.getRedirectUri();
        this.code = value.getCode();
        this.clientSecret = value.getClientSecret();
        this.clientId = value.getClientId();
        this.grantType = value.getGrantType();
        this.scope = value.getScope();
        this.state = value.getState();
        this.sigma = value.getSigma();
        this.language = value.getLanguage();
        this.active = value.getActive();
        this.metadata = value.getMetadata();
        this.createdAt = value.getCreatedAt();
        this.createdBy = value.getCreatedBy();
        this.updatedAt = value.getUpdatedAt();
        this.updatedBy = value.getUpdatedBy();
        this.appId = value.getAppId();
        this.tenantId = value.getTenantId();
    }

    public OUser(
        String key,
        String redirectUri,
        String code,
        String clientSecret,
        String clientId,
        String grantType,
        String scope,
        String state,
        String sigma,
        String language,
        Boolean active,
        String metadata,
        LocalDateTime createdAt,
        String createdBy,
        LocalDateTime updatedAt,
        String updatedBy,
        String appId,
        String tenantId
    ) {
        this.key = key;
        this.redirectUri = redirectUri;
        this.code = code;
        this.clientSecret = clientSecret;
        this.clientId = clientId;
        this.grantType = grantType;
        this.scope = scope;
        this.state = state;
        this.sigma = sigma;
        this.language = language;
        this.active = active;
        this.metadata = metadata;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
        this.updatedAt = updatedAt;
        this.updatedBy = updatedBy;
        this.appId = appId;
        this.tenantId = tenantId;
    }

    public OUser(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    /**
     * Getter for <code>ZDB.O_USER.KEY</code>. 「key」- OAuth用户ID
     */
    @Override
    public String getKey() {
        return this.key;
    }

    /**
     * Setter for <code>ZDB.O_USER.KEY</code>. 「key」- OAuth用户ID
     */
    @Override
    public OUser setKey(String key) {
        this.key = key;
        return this;
    }

    /**
     * Getter for <code>ZDB.O_USER.REDIRECT_URI</code>. 「redirectUri」- 回调重定向地址
     */
    @Override
    public String getRedirectUri() {
        return this.redirectUri;
    }

    /**
     * Setter for <code>ZDB.O_USER.REDIRECT_URI</code>. 「redirectUri」- 回调重定向地址
     */
    @Override
    public OUser setRedirectUri(String redirectUri) {
        this.redirectUri = redirectUri;
        return this;
    }

    /**
     * Getter for <code>ZDB.O_USER.CODE</code>. 「code」- 系统编号
     */
    @Override
    public String getCode() {
        return this.code;
    }

    /**
     * Setter for <code>ZDB.O_USER.CODE</code>. 「code」- 系统编号
     */
    @Override
    public OUser setCode(String code) {
        this.code = code;
        return this;
    }

    /**
     * Getter for <code>ZDB.O_USER.CLIENT_SECRET</code>. 「clientSecret」- 客户端密钥
     */
    @Override
    public String getClientSecret() {
        return this.clientSecret;
    }

    /**
     * Setter for <code>ZDB.O_USER.CLIENT_SECRET</code>. 「clientSecret」- 客户端密钥
     */
    @Override
    public OUser setClientSecret(String clientSecret) {
        this.clientSecret = clientSecret;
        return this;
    }

    /**
     * Getter for <code>ZDB.O_USER.CLIENT_ID</code>. 「clientId」- 客户端ID
     */
    @Override
    public String getClientId() {
        return this.clientId;
    }

    /**
     * Setter for <code>ZDB.O_USER.CLIENT_ID</code>. 「clientId」- 客户端ID
     */
    @Override
    public OUser setClientId(String clientId) {
        this.clientId = clientId;
        return this;
    }

    /**
     * Getter for <code>ZDB.O_USER.GRANT_TYPE</code>. 「grantType」- 认证方式
     */
    @Override
    public String getGrantType() {
        return this.grantType;
    }

    /**
     * Setter for <code>ZDB.O_USER.GRANT_TYPE</code>. 「grantType」- 认证方式
     */
    @Override
    public OUser setGrantType(String grantType) {
        this.grantType = grantType;
        return this;
    }

    /**
     * Getter for <code>ZDB.O_USER.SCOPE</code>. 「scope」- 对应名空间，以应用为中心
     */
    @Override
    public String getScope() {
        return this.scope;
    }

    /**
     * Setter for <code>ZDB.O_USER.SCOPE</code>. 「scope」- 对应名空间，以应用为中心
     */
    @Override
    public OUser setScope(String scope) {
        this.scope = scope;
        return this;
    }

    /**
     * Getter for <code>ZDB.O_USER.STATE</code>. 「state」- 客户端状态
     */
    @Override
    public String getState() {
        return this.state;
    }

    /**
     * Setter for <code>ZDB.O_USER.STATE</code>. 「state」- 客户端状态
     */
    @Override
    public OUser setState(String state) {
        this.state = state;
        return this;
    }

    /**
     * Getter for <code>ZDB.O_USER.SIGMA</code>. 「sigma」- 用户组绑定的统一标识
     */
    @Override
    public String getSigma() {
        return this.sigma;
    }

    /**
     * Setter for <code>ZDB.O_USER.SIGMA</code>. 「sigma」- 用户组绑定的统一标识
     */
    @Override
    public OUser setSigma(String sigma) {
        this.sigma = sigma;
        return this;
    }

    /**
     * Getter for <code>ZDB.O_USER.LANGUAGE</code>. 「language」- 使用的语言
     */
    @Override
    public String getLanguage() {
        return this.language;
    }

    /**
     * Setter for <code>ZDB.O_USER.LANGUAGE</code>. 「language」- 使用的语言
     */
    @Override
    public OUser setLanguage(String language) {
        this.language = language;
        return this;
    }

    /**
     * Getter for <code>ZDB.O_USER.ACTIVE</code>. 「active」- 是否启用
     */
    @Override
    public Boolean getActive() {
        return this.active;
    }

    /**
     * Setter for <code>ZDB.O_USER.ACTIVE</code>. 「active」- 是否启用
     */
    @Override
    public OUser setActive(Boolean active) {
        this.active = active;
        return this;
    }

    /**
     * Getter for <code>ZDB.O_USER.METADATA</code>. 「metadata」- 附加配置数据
     */
    @Override
    public String getMetadata() {
        return this.metadata;
    }

    /**
     * Setter for <code>ZDB.O_USER.METADATA</code>. 「metadata」- 附加配置数据
     */
    @Override
    public OUser setMetadata(String metadata) {
        this.metadata = metadata;
        return this;
    }

    /**
     * Getter for <code>ZDB.O_USER.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    @Override
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>ZDB.O_USER.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    @Override
    public OUser setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>ZDB.O_USER.CREATED_BY</code>. 「createdBy」- 创建人
     */
    @Override
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>ZDB.O_USER.CREATED_BY</code>. 「createdBy」- 创建人
     */
    @Override
    public OUser setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Getter for <code>ZDB.O_USER.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    @Override
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>ZDB.O_USER.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    @Override
    public OUser setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    /**
     * Getter for <code>ZDB.O_USER.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    @Override
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    /**
     * Setter for <code>ZDB.O_USER.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    @Override
    public OUser setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
        return this;
    }

    /**
     * Getter for <code>ZDB.O_USER.APP_ID</code>. 「appId」- 应用ID
     */
    @Override
    public String getAppId() {
        return this.appId;
    }

    /**
     * Setter for <code>ZDB.O_USER.APP_ID</code>. 「appId」- 应用ID
     */
    @Override
    public OUser setAppId(String appId) {
        this.appId = appId;
        return this;
    }

    /**
     * Getter for <code>ZDB.O_USER.TENANT_ID</code>. 「tenantId」- 租户ID
     */
    @Override
    public String getTenantId() {
        return this.tenantId;
    }

    /**
     * Setter for <code>ZDB.O_USER.TENANT_ID</code>. 「tenantId」- 租户ID
     */
    @Override
    public OUser setTenantId(String tenantId) {
        this.tenantId = tenantId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OUser other = (OUser) obj;
        if (this.key == null) {
            if (other.key != null)
                return false;
        } else if (!this.key.equals(other.key))
            return false;
        if (this.redirectUri == null) {
            if (other.redirectUri != null)
                return false;
        } else if (!this.redirectUri.equals(other.redirectUri))
            return false;
        if (this.code == null) {
            if (other.code != null)
                return false;
        } else if (!this.code.equals(other.code))
            return false;
        if (this.clientSecret == null) {
            if (other.clientSecret != null)
                return false;
        } else if (!this.clientSecret.equals(other.clientSecret))
            return false;
        if (this.clientId == null) {
            if (other.clientId != null)
                return false;
        } else if (!this.clientId.equals(other.clientId))
            return false;
        if (this.grantType == null) {
            if (other.grantType != null)
                return false;
        } else if (!this.grantType.equals(other.grantType))
            return false;
        if (this.scope == null) {
            if (other.scope != null)
                return false;
        } else if (!this.scope.equals(other.scope))
            return false;
        if (this.state == null) {
            if (other.state != null)
                return false;
        } else if (!this.state.equals(other.state))
            return false;
        if (this.sigma == null) {
            if (other.sigma != null)
                return false;
        } else if (!this.sigma.equals(other.sigma))
            return false;
        if (this.language == null) {
            if (other.language != null)
                return false;
        } else if (!this.language.equals(other.language))
            return false;
        if (this.active == null) {
            if (other.active != null)
                return false;
        } else if (!this.active.equals(other.active))
            return false;
        if (this.metadata == null) {
            if (other.metadata != null)
                return false;
        } else if (!this.metadata.equals(other.metadata))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        } else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        } else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        } else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        if (this.updatedBy == null) {
            if (other.updatedBy != null)
                return false;
        } else if (!this.updatedBy.equals(other.updatedBy))
            return false;
        if (this.appId == null) {
            if (other.appId != null)
                return false;
        } else if (!this.appId.equals(other.appId))
            return false;
        if (this.tenantId == null) {
            if (other.tenantId != null)
                return false;
        } else if (!this.tenantId.equals(other.tenantId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.key == null) ? 0 : this.key.hashCode());
        result = prime * result + ((this.redirectUri == null) ? 0 : this.redirectUri.hashCode());
        result = prime * result + ((this.code == null) ? 0 : this.code.hashCode());
        result = prime * result + ((this.clientSecret == null) ? 0 : this.clientSecret.hashCode());
        result = prime * result + ((this.clientId == null) ? 0 : this.clientId.hashCode());
        result = prime * result + ((this.grantType == null) ? 0 : this.grantType.hashCode());
        result = prime * result + ((this.scope == null) ? 0 : this.scope.hashCode());
        result = prime * result + ((this.state == null) ? 0 : this.state.hashCode());
        result = prime * result + ((this.sigma == null) ? 0 : this.sigma.hashCode());
        result = prime * result + ((this.language == null) ? 0 : this.language.hashCode());
        result = prime * result + ((this.active == null) ? 0 : this.active.hashCode());
        result = prime * result + ((this.metadata == null) ? 0 : this.metadata.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        result = prime * result + ((this.updatedBy == null) ? 0 : this.updatedBy.hashCode());
        result = prime * result + ((this.appId == null) ? 0 : this.appId.hashCode());
        result = prime * result + ((this.tenantId == null) ? 0 : this.tenantId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OUser (");

        sb.append(key);
        sb.append(", ").append(redirectUri);
        sb.append(", ").append(code);
        sb.append(", ").append(clientSecret);
        sb.append(", ").append(clientId);
        sb.append(", ").append(grantType);
        sb.append(", ").append(scope);
        sb.append(", ").append(state);
        sb.append(", ").append(sigma);
        sb.append(", ").append(language);
        sb.append(", ").append(active);
        sb.append(", ").append(metadata);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(updatedBy);
        sb.append(", ").append(appId);
        sb.append(", ").append(tenantId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IOUser from) {
        setKey(from.getKey());
        setRedirectUri(from.getRedirectUri());
        setCode(from.getCode());
        setClientSecret(from.getClientSecret());
        setClientId(from.getClientId());
        setGrantType(from.getGrantType());
        setScope(from.getScope());
        setState(from.getState());
        setSigma(from.getSigma());
        setLanguage(from.getLanguage());
        setActive(from.getActive());
        setMetadata(from.getMetadata());
        setCreatedAt(from.getCreatedAt());
        setCreatedBy(from.getCreatedBy());
        setUpdatedAt(from.getUpdatedAt());
        setUpdatedBy(from.getUpdatedBy());
        setAppId(from.getAppId());
        setTenantId(from.getTenantId());
    }

    @Override
    public <E extends IOUser> E into(E into) {
        into.from(this);
        return into;
    }
}
