/*
 * This file is generated by jOOQ.
 */
package io.zerows.extension.module.mbsecore.domain.tables.pojos;


import io.r2mo.vertx.jooq.shared.internal.VertxPojo;
import io.zerows.extension.module.mbsecore.domain.tables.interfaces.IMModelCat;

import java.time.LocalDateTime;


import static io.r2mo.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * M_MODEL_CAT
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MModelCat implements VertxPojo, IMModelCat {

    private static final long serialVersionUID = 1L;

    private String id;
    private String name;
    private String catName;
    private String sigma;
    private String appId;
    private String tenantId;
    private Boolean active;
    private String language;
    private String metadata;
    private LocalDateTime createdAt;
    private String createdBy;
    private LocalDateTime updatedAt;
    private String updatedBy;

    public MModelCat() {}

    public MModelCat(IMModelCat value) {
        this.id = value.getId();
        this.name = value.getName();
        this.catName = value.getCatName();
        this.sigma = value.getSigma();
        this.appId = value.getAppId();
        this.tenantId = value.getTenantId();
        this.active = value.getActive();
        this.language = value.getLanguage();
        this.metadata = value.getMetadata();
        this.createdAt = value.getCreatedAt();
        this.createdBy = value.getCreatedBy();
        this.updatedAt = value.getUpdatedAt();
        this.updatedBy = value.getUpdatedBy();
    }

    public MModelCat(
        String id,
        String name,
        String catName,
        String sigma,
        String appId,
        String tenantId,
        Boolean active,
        String language,
        String metadata,
        LocalDateTime createdAt,
        String createdBy,
        LocalDateTime updatedAt,
        String updatedBy
    ) {
        this.id = id;
        this.name = name;
        this.catName = catName;
        this.sigma = sigma;
        this.appId = appId;
        this.tenantId = tenantId;
        this.active = active;
        this.language = language;
        this.metadata = metadata;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
        this.updatedAt = updatedAt;
        this.updatedBy = updatedBy;
    }

        public MModelCat(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }

    /**
     * Getter for <code>ZDB.M_MODEL_CAT.ID</code>. 「id」- 分类ID
     */
    @Override
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>ZDB.M_MODEL_CAT.ID</code>. 「id」- 分类ID
     */
    @Override
    public MModelCat setId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>ZDB.M_MODEL_CAT.NAME</code>. 「name」- 定义名称
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>ZDB.M_MODEL_CAT.NAME</code>. 「name」- 定义名称
     */
    @Override
    public MModelCat setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>ZDB.M_MODEL_CAT.CAT_NAME</code>. 「catName」- 分类别名
     */
    @Override
    public String getCatName() {
        return this.catName;
    }

    /**
     * Setter for <code>ZDB.M_MODEL_CAT.CAT_NAME</code>. 「catName」- 分类别名
     */
    @Override
    public MModelCat setCatName(String catName) {
        this.catName = catName;
        return this;
    }

    /**
     * Getter for <code>ZDB.M_MODEL_CAT.SIGMA</code>. 「sigma」- 统一标识
     */
    @Override
    public String getSigma() {
        return this.sigma;
    }

    /**
     * Setter for <code>ZDB.M_MODEL_CAT.SIGMA</code>. 「sigma」- 统一标识
     */
    @Override
    public MModelCat setSigma(String sigma) {
        this.sigma = sigma;
        return this;
    }

    /**
     * Getter for <code>ZDB.M_MODEL_CAT.APP_ID</code>. 「appId」- 应用ID
     */
    @Override
    public String getAppId() {
        return this.appId;
    }

    /**
     * Setter for <code>ZDB.M_MODEL_CAT.APP_ID</code>. 「appId」- 应用ID
     */
    @Override
    public MModelCat setAppId(String appId) {
        this.appId = appId;
        return this;
    }

    /**
     * Getter for <code>ZDB.M_MODEL_CAT.TENANT_ID</code>. 「tenantId」- 租户ID
     */
    @Override
    public String getTenantId() {
        return this.tenantId;
    }

    /**
     * Setter for <code>ZDB.M_MODEL_CAT.TENANT_ID</code>. 「tenantId」- 租户ID
     */
    @Override
    public MModelCat setTenantId(String tenantId) {
        this.tenantId = tenantId;
        return this;
    }

    /**
     * Getter for <code>ZDB.M_MODEL_CAT.ACTIVE</code>. 「active」- 是否启用
     */
    @Override
    public Boolean getActive() {
        return this.active;
    }

    /**
     * Setter for <code>ZDB.M_MODEL_CAT.ACTIVE</code>. 「active」- 是否启用
     */
    @Override
    public MModelCat setActive(Boolean active) {
        this.active = active;
        return this;
    }

    /**
     * Getter for <code>ZDB.M_MODEL_CAT.LANGUAGE</code>. 「language」- 语言
     */
    @Override
    public String getLanguage() {
        return this.language;
    }

    /**
     * Setter for <code>ZDB.M_MODEL_CAT.LANGUAGE</code>. 「language」- 语言
     */
    @Override
    public MModelCat setLanguage(String language) {
        this.language = language;
        return this;
    }

    /**
     * Getter for <code>ZDB.M_MODEL_CAT.METADATA</code>. 「metadata」- 附加配置
     */
    @Override
    public String getMetadata() {
        return this.metadata;
    }

    /**
     * Setter for <code>ZDB.M_MODEL_CAT.METADATA</code>. 「metadata」- 附加配置
     */
    @Override
    public MModelCat setMetadata(String metadata) {
        this.metadata = metadata;
        return this;
    }

    /**
     * Getter for <code>ZDB.M_MODEL_CAT.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    @Override
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>ZDB.M_MODEL_CAT.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    @Override
    public MModelCat setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>ZDB.M_MODEL_CAT.CREATED_BY</code>. 「createdBy」- 创建人
     */
    @Override
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>ZDB.M_MODEL_CAT.CREATED_BY</code>. 「createdBy」- 创建人
     */
    @Override
    public MModelCat setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Getter for <code>ZDB.M_MODEL_CAT.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    @Override
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>ZDB.M_MODEL_CAT.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    @Override
    public MModelCat setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    /**
     * Getter for <code>ZDB.M_MODEL_CAT.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    @Override
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    /**
     * Setter for <code>ZDB.M_MODEL_CAT.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    @Override
    public MModelCat setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final MModelCat other = (MModelCat) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.catName == null) {
            if (other.catName != null)
                return false;
        }
        else if (!this.catName.equals(other.catName))
            return false;
        if (this.sigma == null) {
            if (other.sigma != null)
                return false;
        }
        else if (!this.sigma.equals(other.sigma))
            return false;
        if (this.appId == null) {
            if (other.appId != null)
                return false;
        }
        else if (!this.appId.equals(other.appId))
            return false;
        if (this.tenantId == null) {
            if (other.tenantId != null)
                return false;
        }
        else if (!this.tenantId.equals(other.tenantId))
            return false;
        if (this.active == null) {
            if (other.active != null)
                return false;
        }
        else if (!this.active.equals(other.active))
            return false;
        if (this.language == null) {
            if (other.language != null)
                return false;
        }
        else if (!this.language.equals(other.language))
            return false;
        if (this.metadata == null) {
            if (other.metadata != null)
                return false;
        }
        else if (!this.metadata.equals(other.metadata))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        if (this.updatedBy == null) {
            if (other.updatedBy != null)
                return false;
        }
        else if (!this.updatedBy.equals(other.updatedBy))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.catName == null) ? 0 : this.catName.hashCode());
        result = prime * result + ((this.sigma == null) ? 0 : this.sigma.hashCode());
        result = prime * result + ((this.appId == null) ? 0 : this.appId.hashCode());
        result = prime * result + ((this.tenantId == null) ? 0 : this.tenantId.hashCode());
        result = prime * result + ((this.active == null) ? 0 : this.active.hashCode());
        result = prime * result + ((this.language == null) ? 0 : this.language.hashCode());
        result = prime * result + ((this.metadata == null) ? 0 : this.metadata.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        result = prime * result + ((this.updatedBy == null) ? 0 : this.updatedBy.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MModelCat (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(catName);
        sb.append(", ").append(sigma);
        sb.append(", ").append(appId);
        sb.append(", ").append(tenantId);
        sb.append(", ").append(active);
        sb.append(", ").append(language);
        sb.append(", ").append(metadata);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(updatedBy);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IMModelCat from) {
        setId(from.getId());
        setName(from.getName());
        setCatName(from.getCatName());
        setSigma(from.getSigma());
        setAppId(from.getAppId());
        setTenantId(from.getTenantId());
        setActive(from.getActive());
        setLanguage(from.getLanguage());
        setMetadata(from.getMetadata());
        setCreatedAt(from.getCreatedAt());
        setCreatedBy(from.getCreatedBy());
        setUpdatedAt(from.getUpdatedAt());
        setUpdatedBy(from.getUpdatedBy());
    }

    @Override
    public <E extends IMModelCat> E into(E into) {
        into.from(this);
        return into;
    }
}
